// client-react/src/App.tsx
import { useState } from 'react';
import { Routes, Route, Navigate, useLocation, Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { createPortal } from 'react-dom';
import HomeScreen from './components/HomeScreen';
import RoomScreen from './components/game/RoomScreen';
import CardsPreview from './components/CardsPreview';
import StatsScreen from './components/StatsScreen';
import Preview from './pages/Preview';
import AuthPanel from './components/AuthPanel';
import LocaleSelector from './components/common/LocaleSelector';

// Mirrors Vue App.vue. The About modal (Vue Bootstrap data-toggle) becomes a
// createPortal + local state. Vue computed inGame ($route.name === 'room') →
// useLocation pathname check. Header SCSS extracted to _app.scss.
export default function App() {
  const { t } = useTranslation();
  const location = useLocation();
  const [showAbout, setShowAbout] = useState(false);

  const inGame = location.pathname.startsWith('/room');

  return (
    <div className="d-flex flex-column h-100">
      <header>
        <div className="container-fluid">
          <div className="d-flex flex-wrap align-items-center justify-content-end">
            <div className="flex-grow-1 text-center pb-1">
              <h1><a href="/" className="text-reset">{t('ui.title')}</a></h1>
              <h6 className={inGame ? 'header-subtitle--hidden' : ''}>{t('ui.subtitle2')}</h6>
            </div>
            <div className="text-right header-actions">
              <AuthPanel />
              <div className={`mb-1 header-extra${inGame ? ' header-extra--hidden' : ''}`}>
                <Link className="text-reset text-decoration-none mr-2" to="/stats">
                  {t('ui.stats.title')}
                </Link>
                <button
                  type="button"
                  className="text-reset text-decoration-none btn btn-link p-0"
                  onClick={() => setShowAbout(true)}
                >
                  {t('ui.about.title')}
                </button>
              </div>
              <LocaleSelector />
            </div>
          </div>
        </div>
      </header>

      <div className={`body flex-fill${inGame ? ' body--game' : ''}`}>
        <Routes>
          <Route path="/" element={<HomeScreen />} />
          <Route path="/room/:roomId" element={<RoomScreen />} />
          <Route path="/cards" element={<CardsPreview />} />
          <Route path="/stats" element={<StatsScreen />} />
          <Route path="/preview" element={<Preview />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </div>

      {showAbout && createPortal(
        <div className="modal fade show d-block" style={{ background: 'rgba(0,0,0,0.65)', zIndex: 1050 }}>
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h5 className="modal-title">{t('ui.about.title')}</h5>
                <button type="button" className="close" aria-label={t('ui.close') as string} onClick={() => setShowAbout(false)}>
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div className="modal-body">
                {/* eslint-disable-next-line react/no-danger */}
                <p dangerouslySetInnerHTML={{ __html: t('ui.about.text') as string }} />
              </div>
            </div>
          </div>
        </div>,
        document.body,
      )}
    </div>
  );
}

// client/src/App.vue
<template>
<div
  class="modal fade"
  id="aboutModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ $t('ui.about.title') }}</h5>
        <button type="button" class="close" data-dismiss="modal" :aria-label="$t('ui.close')">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p v-html="$t('ui.about.text')"></p>
        <h6>{{ $t('ui.about.picture_credits') }}</h6>
        <ul>
          <li
            v-for="line, i in credits"
            :key="i"
          >
            <a :href="line[1]" target="_blank">{{ $t(`districts.${line[0]}.name`) }}</a>
            {{ $t('ui.about.by') }}
            <a v-if="line[3]" :href="line[3]" target="_blank">{{ line[2] }}</a>
            <span v-else>{{ line[2] }}</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="d-flex flex-column h-100">
<header v-if="!inGame">
  <div class="container-fluid">
    <div class="d-flex flex-wrap align-items-center justify-content-end">
      <div class="flex-grow-1 text-center pb-1">
        <h1><a href="/" class="text-reset">{{ $t('ui.title') }}</a></h1>
        <h6>{{ $t('ui.subtitle2') }}</h6>
      </div>
      <div class="text-right">
        <AuthPanel class="mb-1" />
        <div class="mb-1">
          <router-link class="text-reset text-decoration-none mr-2" :to="{ name: 'stats' }">
            {{ $t('ui.stats.title') }}
          </router-link>
        </div>
        <LocaleSelector class="opacity-4" />
        <a
          class="text-reset text-decoration-none"
          href="#"
          data-toggle="modal"
          data-target="#aboutModal"
        >{{ $t('ui.about.title') }}</a>
      </div>
    </div>
  </div>
</header>
<header v-else class="header-in-game">
  <div class="container-fluid">
    <div class="d-flex flex-wrap align-items-center justify-content-end gap-3 py-0">
      <div class="flex-grow-1 text-center">
        <h2 class="mt-0 mb-0 h5"><a href="/" class="text-reset">{{ $t('ui.title') }}</a></h2>
      </div>
      <div>
        <AuthPanel class="mb-0" />
      </div>
      <div>
        <LocaleSelector class="opacity-4" />
      </div>
    </div>
  </div>
</header>
<div class="body flex-fill" :class="{ 'body--game': inGame }">
  <router-view></router-view>
</div>
</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import LocaleSelector from './components/LocaleSelector.vue';
import AuthPanel from './components/AuthPanel.vue';
import credits from './data/credits.json';
import { store } from './store';

export default defineComponent({
  name: 'App',
  components: {
    LocaleSelector,
    AuthPanel,
  },
  computed: {
    credits() {
      return credits;
    },
    inGame() {
      return this.$route.name === 'room';
    },
  },
  created() {
    store.dispatch('initAuth');
  },
});
</script>

<style lang="scss" scoped>
header {
  background: brown;
  color: wheat;
  margin: 0;
  padding: 0.5em;

  h1, h2, h6 {
    padding: 0;
    margin: 0;
  }
}

.body {
  background: wheat;
  min-height: 0;
}

.body--game {
  background: #1a1410;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.header-in-game {
  padding: 0.25rem 0.5rem !important;
  background: #1a1410 !important;
  border-bottom: 1px solid rgba(212, 175, 55, 0.25);
}
</style>
