// client-react/src/components/common/Modal.tsx
import { ReactNode } from 'react';
import { createPortal } from 'react-dom';

interface ModalProps {
  show: boolean;
  title?: string;
  dialogClass?: string;
  headerClass?: string;
  onClose?: () => void;
  children?: ReactNode;
  footer?: ReactNode;
}

// Replaces Vue's common/Modal.vue. Uses a portal to document.body so the
// overlay escapes any transformed/clipped ancestor. Bootstrap 4 modal classes
// are reused from the shared SCSS; no jQuery/Bootstrap JS dependency.
export default function Modal({
  show,
  title = '',
  dialogClass = 'modal-dialog-centered',
  headerClass = '',
  onClose,
  children,
  footer,
}: ModalProps) {
  if (!show) return null;
  return createPortal(
    <div className="modal fade show d-block" style={{ background: 'rgba(0,0,0,0.65)', zIndex: 1050 }}>
      <div className={`modal-dialog ${dialogClass}`}>
        <div className="modal-content">
          <div className={`modal-header ${headerClass}`}>
            <h5 className="modal-title mb-0">{title}</h5>
            <button type="button" className="close text-white" onClick={onClose} aria-label="close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div className="modal-body">{children}</div>
          {footer && <div className="modal-footer">{footer}</div>}
        </div>
      </div>
    </div>,
    document.body,
  );
}

// client/src/components/common/Modal.vue
<template>
  <div v-if="show" class="modal fade show d-block" style="background:rgba(0,0,0,0.65); z-index: 1050;">
    <div class="modal-dialog" :class="dialogClass">
      <div class="modal-content">
        <div class="modal-header" :class="headerClass">
          <h5 class="modal-title mb-0">{{ title }}</h5>
          <button
            type="button"
            class="close text-white"
            @click="$emit('close')"
            aria-label="close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <slot />
        </div>
        <div v-if="$slots.footer" class="modal-footer">
          <slot name="footer" />
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'AppModal',
  props: {
    show: {
      type: Boolean,
      required: true,
    },
    title: {
      type: String,
      default: '',
    },
    dialogClass: {
      type: String,
      default: 'modal-dialog-centered',
    },
    headerClass: {
      type: String,
      default: '',
    },
  },
  emits: ['close'],
});
</script>
