// client/src/components/game/BoardScreen.vue
<template>
  <div class="board-table">
    <div class="board-table__bg" />

    <!-- Top: team scores + turn order -->
    <div class="board-table__top">
      <div v-if="showTeamScores" class="board-table__score-bar">
        <span class="board-table__team-a">
          {{ isSpectator ? $t('ui.team.a') : $t('ui.team.mine') }}
          {{ liveTeamScores.A }}
        </span>
        <span class="opacity-50">VS</span>
        <span class="board-table__team-b">
          {{ isSpectator ? $t('ui.team.b') : $t('ui.team.enemy') }}
          {{ liveTeamScores.B }}
        </span>
      </div>
      <TurnOrderBar
        :turn-order-chips="turnOrderChips"
        :game-progress="gameProgress"
      />
      <button type="button" class="board-table__leave-btn" @click="leaveRoom">
        {{ $t('ui.score.leave_room') }}
      </button>
    </div>

    <div class="board-table__stage" :class="{ 'board-table__stage--spectate': isSpectator }">
      <!-- Seats: player = 5 opponents + self bottom; spectator = 6 seats L3+R3 -->
      <div
        v-for="slot in tableSlots"
        :key="slot.playerId"
        class="board-table__slot"
        :class="`board-table__slot--${slot.pos}`"
      >
        <SeatPanel
          :player-id="slot.playerId"
          :board="slot.board"
          :pick-order="slot.pickOrder"
          :destroy-mode="destroyMode"
          :exchange-hand-mode="exchangeHandMode"
          :stash="selfBoard.stash"
          :relation="slot.relation"
        />
      </div>

      <!-- Center: character selection / status / draft -->
      <CenterPanel
        :game-progress="gameProgress"
        :characters-list="charactersList"
        :game-state="gameState"
        :kill-mode="killMode"
        :rob-mode="robMode"
        :choose-character-mode="chooseCharacterMode"
        :event-banner="eventBanner"
        @select-character="onCenterCharacterClick"
      />

      <!-- Self strip: only when seated player (not spectator) -->
      <div v-if="!isSpectator" class="board-table__slot board-table__slot--self">
        <div class="board-table__self-wrap">
          <div class="board-table__self-panel">
            <div class="board-table__self-banner">
              <span class="board-table__self-pick">{{ selfPickOrder }}</span>
              <span class="text-truncate flex-fill">{{ selfName }}</span>
              <span class="board-table__self-vp">
                ⭐ {{ selfBoard.score?.total ?? 0 }}
              </span>
              <span
                v-if="selfBoard.crown"
                class="seat-panel__crown"
                :title="$t('ui.game.crown_holder')"
              >👑</span>
              <span class="seat-panel__tag">{{ $t('ui.lobby.you') }}</span>
            </div>
            <div class="board-table__self-body">
              <div class="board-table__self-city">
                <DistrictCard
                  v-for="(id, i) in selfBoard.city"
                  :key="'city-' + i"
                  :district-id="id"
                  small
                />
                <div v-if="!(selfBoard.city || []).length" class="seat-panel__city-empty">
                  {{ $t('ui.game.no_buildings') }}
                </div>
              </div>
              <div class="board-table__self-role">
                <CharacterCard
                  v-if="gameProgress === 'IN_GAME' && selfRoleCard.show"
                  :character-id="selfRoleCard.id"
                  :face-down="selfRoleCard.faceDown"
                  :killed="selfRoleCard.killed"
                  :robbed="selfRoleCard.robbed"
                  size="medium"
                />
              </div>
            </div>
            <div class="board-table__self-hand">
              <PlayerHand
                :board="selfBoard"
                :build-mode="buildMode"
                :discard-cards-mode="discardCardsMode"
                :laboratory-mode="laboratoryMode"
              />
            </div>
          </div>
        </div>

        <ActionPanel
          :actions="statusBar.actions"
          :game-progress="gameProgress"
          :countdown-text="countdownText"
          :countdown-urgent="countdownUrgent"
          :is-autoplay="selfIsAutoplay"
          :autoplay-busy="autoplayBusy"
          @action="sendMove"
          @toggle-autoplay="toggleAutoplay"
        />
      </div>

      <!-- Far right: action log (server feed) -->
      <ActionLog
        :display-action-feed="displayActionFeed"
        @show-event="showEvent"
      />
    </div>

    <!-- End game: dismissible result; stay on board until leave -->
    <EndGameModal
      :show="gameProgress === 'FINISHED' && showEndModal"
      :game-state="gameState"
      :self-id="self"
      :is-spectator="isSpectator"
      :show-team-scores="showTeamScores"
      :get-player-from-id="getPlayerFromId"
      @close="dismissEndModal"
      @leave="backToLobby"
    />

    <!-- floating reopen + leave when modal dismissed -->
    <div
      v-if="gameProgress === 'FINISHED' && !showEndModal"
      class="board-table__end-bar"
    >
      <button type="button" class="btn btn-sm btn-warning mr-2" @click="showEndModal = true">
        {{ $t('ui.score.show_result') }}
      </button>
      <button type="button" class="btn btn-sm btn-outline-light" @click="backToLobby">
        {{ $t('ui.score.leave_room') }}
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { mapGetters } from 'vuex';
import {
  CharacterChoosingStateType as CCST,
  ClientTurnState,
  computeTeamScores,
  GameMode,
  getMyTeam as getMyTeamOf,
  getRelation,
  getSeatOrder,
  getTableSlots,
  isSpectator as isSpectatorOf,
  Move,
  MoveType,
  TeamId,
} from 'citadels-common';
import { store } from '../../store';
import SeatPanel from './elements/SeatPanel.vue';
import PlayerHand from './elements/PlayerHand.vue';
import DistrictCard from './elements/DistrictCard.vue';
import CharacterCard from './elements/CharacterCard.vue';
import { getStatusBarData } from '../../data/statusBarData';
import TurnOrderBar from './TurnOrderBar.vue';
import ActionLog from './ActionLog.vue';
import ActionPanel from './ActionPanel.vue';
import CenterPanel from './CenterPanel.vue';
import EndGameModal from './EndGameModal.vue';

export default defineComponent({
  components: {
    SeatPanel,
    PlayerHand,
    DistrictCard,
    CharacterCard,
    TurnOrderBar,
    ActionLog,
    ActionPanel,
    CenterPanel,
    EndGameModal,
  },
  name: 'BoardScreen',
  data() {
    return {
      startingGame: false,
      nowMs: Date.now(),
      countdownTimer: 0 as any,
      autoplayBusy: false,
      eventBanner: '',
      eventBannerTimer: 0 as any,
      lastKilledId: 0,
      lastRobbedId: 0,
      lastCurrentChar: 0,
      lastStatusKey: '',
      actionLog: [] as { text: string; kind?: string }[],
      /** end-game result dialog; can dismiss without leaving room */
      showEndModal: true,
      showSetupConfirm: false,
      _isUnmounted: false,
    };
  },
  computed: {
    ...mapGetters([
      'getPlayerFromId',
      'gameSetupData',
      'gameState',
      'charactersList',
      'isCurrentPlayerSelf',
      'gameProgress',
    ]),
    self() {
      return this.gameState.self;
    },
    selfIsAutoplay() {
      const me = this.getPlayerFromId(this.self);
      return Boolean(me?.isAutoplay);
    },
    countdownSecondsLeft() {
      const deadline = this.gameState?.turnDeadlineAt;
      if (!deadline) return null;
      return Math.max(0, Math.ceil((deadline - this.nowMs) / 1000));
    },
    countdownText() {
      if (this.selfIsAutoplay) return this.$t('ui.game.countdown_autoplay');
      if (this.countdownSecondsLeft === null) return '—';
      const s = this.countdownSecondsLeft;
      const m = Math.floor(s / 60);
      const r = s % 60;
      return m > 0 ? `${m}:${String(r).padStart(2, '0')}` : `${s}s`;
    },
    countdownUrgent() {
      return this.countdownSecondsLeft !== null && this.countdownSecondsLeft <= 15;
    },
    isSpectator() {
      if (!this.gameState) return true;
      return isSpectatorOf(this.gameState);
    },
    myTeam() {
      if (!this.gameState) return null;
      return getMyTeamOf(this.gameState, this.isSpectator);
    },
    relationOf() {
      return (playerId: string) => {
        if (!this.gameState) return 'self' as const;
        return getRelation(this.gameState, playerId, this.isSpectator);
      };
    },
    seatOrder() {
      if (!this.gameState) return [];
      return getSeatOrder(this.gameState, this.isSpectator);
    },
    tableSlots() {
      if (!this.gameState) return [];
      return getTableSlots(this.gameState, this.isSpectator);
    },
    selfBoard() {
      if (this.isSpectator) {
        return {
          stash: 0, hand: [], tmpHand: [], city: [], score: {}, characters: [], crown: false,
        };
      }
      const board = this.gameState.board.players[this.self];
      return {
        stash: 0,
        hand: [],
        tmpHand: [],
        city: [],
        score: {},
        characters: [],
        ...(board || {}),
        crown: this.gameState.board.playerOrder[0] === this.self,
      };
    },
    selfName() {
      return this.getPlayerFromId(this.self)?.username || 'You';
    },
    selfPickOrder() {
      const order = this.gameState?.board?.playerOrder || [];
      const idx = order.indexOf(this.self);
      return idx >= 0 ? idx + 1 : 0;
    },
    displayActionFeed() {
      return this.gameState?.actionFeed || this.actionLog || [];
    },
    selfRoleCard() {
      const chars = this.selfBoard?.characters || [];
      if (!chars.length) {
        return {
          show: false, id: 0, faceDown: true, killed: false, robbed: false,
        };
      }
      const revealed = chars.find((c: any) => c.id > 0);
      if (revealed) {
        return {
          show: true,
          id: revealed.id,
          faceDown: false,
          killed: Boolean(revealed.killed),
          robbed: Boolean(revealed.robbed),
        };
      }
      return {
        show: true,
        id: 0,
        faceDown: true,
        killed: false,
        robbed: false,
      };
    },
    statusBar() {
      return getStatusBarData(this.gameState);
    },
    buildMode() {
      return !this.isSpectator && this.isCurrentPlayerSelf
        && this.gameState.board.turnState === ClientTurnState.BUILD_DISTRICT;
    },
    destroyMode() {
      return !this.isSpectator && this.isCurrentPlayerSelf
        && this.gameState.board.turnState === ClientTurnState.WARLORD_DESTROY_DISTRICT;
    },
    killMode() {
      return !this.isSpectator && this.isCurrentPlayerSelf
        && this.gameState.board.turnState === ClientTurnState.ASSASSIN_KILL;
    },
    robMode() {
      return !this.isSpectator && this.isCurrentPlayerSelf
        && this.gameState.board.turnState === ClientTurnState.THIEF_ROB;
    },
    putAsideMode() {
      if (this.isSpectator || !this.isCurrentPlayerSelf) return false;
      switch (this.gameState.board.characters.state.type) {
        case CCST.PUT_ASIDE_FACE_UP:
        case CCST.PUT_ASIDE_FACE_DOWN:
        case CCST.PUT_ASIDE_FACE_DOWN_UP:
          return true;
        default:
          return false;
      }
    },
    chooseCharacterMode() {
      if (this.isSpectator || !this.isCurrentPlayerSelf) return false;
      return this.gameState.board.characters?.state?.type === CCST.CHOOSE_CHARACTER
        || this.putAsideMode;
    },
    exchangeHandMode() {
      return !this.isSpectator && this.isCurrentPlayerSelf
        && this.gameState.board.turnState === ClientTurnState.MAGICIAN_EXCHANGE_HAND;
    },
    discardCardsMode() {
      return !this.isSpectator && this.isCurrentPlayerSelf
        && this.gameState.board.turnState === ClientTurnState.MAGICIAN_DISCARD_CARDS;
    },
    laboratoryMode() {
      return !this.isSpectator && this.isCurrentPlayerSelf
        && this.gameState.board.turnState === ClientTurnState.LABORATORY_DISCARD_CARD;
    },
    isCompetitive() {
      return this.gameState?.gameMode === GameMode.COMPETITIVE_TEAM6;
    },
    showTeamScores() {
      if (!this.gameState?.board?.playerOrder) return false;
      return Object.values(this.gameState.players).some(
        (p: any) => p.team === TeamId.A || p.team === TeamId.B,
      );
    },
    liveTeamScores() {
      if (!this.gameState) return { A: 0, B: 0, myLabel: 'A', enemyLabel: 'B' };
      const { A, B } = computeTeamScores(this.gameState);
      if (!this.isSpectator && this.myTeam === TeamId.B) {
        return { A: B, B: A, myLabel: 'B', enemyLabel: 'A' };
      }
      return { A, B, myLabel: 'A', enemyLabel: 'B' };
    },
    turnOrderChips() {
      const list = this.charactersList?.callable || [];
      const current = this.charactersList?.current || 0;
      if (list.length) {
        return list.map((c: any, idx: number) => ({
          idx,
          id: c.id || 0,
          current: c.id === current && current !== 0,
          killed: Boolean(c.killed),
          faceUp: Boolean(c.faceUp || c.discardedFaceUp),
          tip: c.id
            ? this.$t(`characters.${c.id}.name`)
            : this.$t('ui.game.character_unknown'),
        }));
      }
      return [1, 2, 3, 4, 5, 6, 7, 8].map((id, idx) => ({
        idx, id, current: id === current, killed: false, faceUp: false, tip: '',
      }));
    },
  },
  methods: {
    isPrimaryAction(title: string) {
      return ['take_gold', 'draw_cards', 'draw_cards_3', 'build_district', 'confirm', 'accept']
        .includes(title);
    },
    async onCenterCharacterClick(ch: any, index: number) {
      if (!ch.selectable) return;
      let moveType = MoveType.CHOOSE_CHARACTER;
      let moveData: any = index;
      if (this.killMode) {
        moveType = MoveType.ASSASSIN_KILL;
        moveData = ch.id;
      } else if (this.robMode) {
        moveType = MoveType.THIEF_ROB;
        moveData = ch.id;
      }
      try {
        await store.dispatch('sendMove', { type: moveType, data: moveData });
      } catch (e) {
        console.log('character click failed', e);
      }
    },
    showConfirmationModal() {
      store.commit('prepareGameSetupConfirmation');
      this.showSetupConfirm = true;
    },
    async startGame() {
      this.startingGame = true;
      try {
        await store.dispatch('startGame');
        this.startingGame = false;
      } catch (error) {
        console.error('error when starting game', error);
        this.startingGame = false;
      }
    },
    async toggleAutoplay() {
      if (this.autoplayBusy) return;
      this.autoplayBusy = true;
      try {
        await store.dispatch('setAutoplay', !this.selfIsAutoplay);
      } catch (error) {
        console.error('autoplay toggle failed', error);
      } finally {
        this.autoplayBusy = false;
      }
    },
    async sendMove(move: Move, target: HTMLElement) {
      if (target && target.blur) target.blur();
      try {
        await store.dispatch('sendMove', move);
      } catch (error) {
        console.log('error when sending move', error);
      }
    },
    dismissEndModal() {
      this.showEndModal = false;
    },
    async backToLobby() {
      try {
        await store.dispatch('leaveRoom');
      } catch (e) {
        console.error('leave room failed', e);
      }
      this.$router.push('/').catch(() => {
        window.location.href = '/';
      });
    },
    async leaveRoom() {
      try {
        await store.dispatch('leaveRoom');
        this.$router.push('/').catch(() => {
          window.location.href = '/';
        });
      } catch (e) {
        console.error('leave room failed', e);
      }
    },
    showEvent(text: string) {
      this.eventBanner = text;
      if (this.eventBannerTimer) clearTimeout(this.eventBannerTimer);
      this.eventBannerTimer = setTimeout(() => {
        this.eventBanner = '';
      }, 3500);
    },
  },
  mounted() {
    this.countdownTimer = setInterval(() => {
      this.nowMs = Date.now();
    }, 250);
  },
  beforeUnmount() {
    this._isUnmounted = true;
    if (this.countdownTimer) clearInterval(this.countdownTimer);
    if (this.eventBannerTimer) clearTimeout(this.eventBannerTimer);
    this.showSetupConfirm = false;
  },
  watch: {
    gameProgress(val: string) {
      if (val === 'FINISHED') this.showEndModal = true;
    },
    displayActionFeed: {
      deep: true,
      handler(list: any[]) {
        if (!Array.isArray(list) || !list.length) return;
        const last = list[list.length - 1];
        if (last?.kind === 'kill' || last?.kind === 'rob') {
          this.showEvent(last.text);
        }
        this.$nextTick(() => {
          if (this._isUnmounted) return;
          const el = this.$refs.actionLogList as HTMLElement | undefined;
          if (el) el.scrollTop = el.scrollHeight;
        });
      },
    },
  },
});
</script>

<style lang="scss" scoped>
.board-table__end-bar {
  position: absolute;
  right: 1rem;
  bottom: 1rem;
  z-index: 20;
  display: flex;
  align-items: center;
  padding: 0.5rem 0.75rem;
  border-radius: 10px;
  background: rgba(0, 0, 0, 0.75);
  border: 1px solid rgba(212, 175, 55, 0.4);
  box-shadow: 0 6px 20px rgba(0, 0, 0, 0.45);
}
.board-table__leave-btn {
  position: absolute;
  top: 0.5rem;
  right: 0.5rem;
  z-index: 20;
  background: rgba(0, 0, 0, 0.6);
  border: 1px solid rgba(212, 175, 55, 0.45);
  color: var(--gold);
  border-radius: 0.35rem;
  padding: 0.35rem 0.6rem;
  font-size: 0.8rem;
  cursor: pointer;
  transition: all 0.2s ease;
}
.board-table__leave-btn:hover {
  background: rgba(212, 175, 55, 0.15);
  border-color: var(--gold-bright);
  color: var(--gold-bright);
}
</style>

// client-react/src/components/game/BoardScreen.tsx
import {
  useEffect, useMemo, useRef, useState,
} from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  CharacterChoosingStateType as CCST,
  ClientTurnState,
  computeTeamScores,
  getMyTeam as getMyTeamOf,
  getTableSlots,
  isSpectator as isSpectatorOf,
  Move,
  MoveType,
  TeamId,
  type TableSlot,
  type DistrictId,
} from 'citadels-common';
import { useStatusBarData } from '@/data/useStatusBarData';
import {
  useAppStore,
  useGameProgress,
  useGameState,
  useIsCurrentPlayerSelf,
  useCharactersList,
  selectPlayerFromId,
} from '@/store';
import SeatPanel from './elements/SeatPanel';
import PlayerHand from './elements/PlayerHand';
import DistrictCard from './elements/DistrictCard';
import CharacterCard from './elements/CharacterCard';
import TurnOrderBar from './TurnOrderBar';
import ActionLog from './ActionLog';
import ActionPanel from './ActionPanel';
import CenterPanel from './CenterPanel';
import EndGameModal from './EndGameModal';

// Mirrors Vue BoardScreen.vue (561 lines). The orchestration component that
// assembles all migrated subcomponents. Vue data() → useState; computed →
// useMemo; mounted/beforeUnmount timers → useEffect with cleanup; watch
// blocks → useEffect on the watched dependency.
export default function BoardScreen() {
  const { t } = useTranslation();
  const navigate = useNavigate();

  const gameState = useGameState();
  const gameProgress = useGameProgress();
  const isCurrentPlayerSelf = useIsCurrentPlayerSelf();
  const charactersList = useCharactersList();
  const sendMoveStore = useAppStore((s) => s.sendMove);
  const leaveRoomStore = useAppStore((s) => s.leaveRoom);
  const setAutoplayStore = useAppStore((s) => s.setAutoplay);

  // --- local UI state (was Vue data()) ---
  const [nowMs, setNowMs] = useState(Date.now());
  const [autoplayBusy, setAutoplayBusy] = useState(false);
  const [eventBanner, setEventBanner] = useState('');
  const [showEndModal, setShowEndModal] = useState(true);
  const eventBannerTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  // --- countdown timer (was Vue mounted()) ---
  useEffect(() => {
    const id = setInterval(() => setNowMs(Date.now()), 250);
    return () => clearInterval(id);
  }, []);

  // --- cleanup event banner timer on unmount (was Vue beforeUnmount) ---
  useEffect(() => () => {
    if (eventBannerTimer.current) clearTimeout(eventBannerTimer.current);
  }, []);

  // --- watch gameProgress → reset showEndModal when entering FINISHED ---
  useEffect(() => {
    if (gameProgress === 'FINISHED') setShowEndModal(true);
  }, [gameProgress]);

  const statusBar = useStatusBarData(gameState);

  // --- derived state (was Vue computed) ---
  const self = gameState?.self ?? '';
  const getPlayer = selectPlayerFromId(gameState);
  const selfMeta = self ? getPlayer(self) : undefined;
  const selfIsAutoplay = Boolean(selfMeta?.isAutoplay);

  const countdownSecondsLeft = useMemo(() => {
    const deadline = gameState?.turnDeadlineAt;
    if (!deadline) return null;
    return Math.max(0, Math.ceil((deadline - nowMs) / 1000));
  }, [gameState?.turnDeadlineAt, nowMs]);

  const countdownText = useMemo(() => {
    if (selfIsAutoplay) return t('ui.game.countdown_autoplay');
    if (countdownSecondsLeft === null) return '—';
    const s = countdownSecondsLeft;
    const m = Math.floor(s / 60);
    const r = s % 60;
    return m > 0 ? `${m}:${String(r).padStart(2, '0')}` : `${s}s`;
  }, [selfIsAutoplay, countdownSecondsLeft, t]);

  const countdownUrgent = countdownSecondsLeft !== null && countdownSecondsLeft <= 15;

  const isSpectator = useMemo(() => (gameState ? isSpectatorOf(gameState) : true), [gameState]);
  const myTeam = useMemo(() => (gameState ? getMyTeamOf(gameState, isSpectator) : null), [gameState, isSpectator]);

  const tableSlots = useMemo<TableSlot[]>(() => (gameState ? getTableSlots(gameState, isSpectator) : []), [gameState, isSpectator]);

  const selfBoard = useMemo(() => {
    if (isSpectator || !gameState) {
      return {
        stash: 0, hand: [], tmpHand: [], city: [], score: {}, characters: [], crown: false,
      } as const;
    }
    const board = gameState.board.players[self] as Record<string, unknown> | undefined;
    return {
      stash: 0,
      hand: [],
      tmpHand: [],
      city: [],
      score: {},
      characters: [],
      ...(board || {}),
      crown: gameState.board.playerOrder[0] === self,
    };
  }, [gameState, isSpectator, self]);

  const selfName = self ? (getPlayer(self)?.username || 'You') : 'You';
  const selfPickOrder = useMemo(() => {
    const order = gameState?.board?.playerOrder || [];
    const idx = order.indexOf(self);
    return idx >= 0 ? idx + 1 : 0;
  }, [gameState?.board?.playerOrder, self]);

  const displayActionFeed = useMemo(() => gameState?.actionFeed || [], [gameState?.actionFeed]);

  const selfRoleCard = useMemo(() => {
    const chars = (selfBoard?.characters || []) as Array<{ id: number; faceDown?: boolean; killed?: boolean; robbed?: boolean }>;
    if (!chars.length) {
      return {
        show: false, id: 0, faceDown: true, killed: false, robbed: false,
      };
    }
    const revealed = chars.find((c) => c.id > 0);
    if (revealed) {
      return {
        show: true,
        id: revealed.id,
        faceDown: false,
        killed: Boolean(revealed.killed),
        robbed: Boolean(revealed.robbed),
      };
    }
    return {
      show: true, id: 0, faceDown: true, killed: false, robbed: false,
    };
  }, [selfBoard]);

  const modeFlags = useMemo(() => {
    if (!gameState) {
      return {
        build: false,
        destroy: false,
        kill: false,
        rob: false,
        putAside: false,
        chooseChar: false,
        exchangeHand: false,
        discardCards: false,
        laboratory: false,
      };
    }
    const seated = !isSpectator && isCurrentPlayerSelf;
    const ts = gameState.board.turnState;
    const charStateType = gameState.board.characters?.state?.type;
    const putAside = seated && (charStateType === CCST.PUT_ASIDE_FACE_UP
      || charStateType === CCST.PUT_ASIDE_FACE_DOWN
      || charStateType === CCST.PUT_ASIDE_FACE_DOWN_UP);
    const chooseChar = seated && (charStateType === CCST.CHOOSE_CHARACTER || putAside);
    return {
      build: seated && ts === ClientTurnState.BUILD_DISTRICT,
      destroy: seated && ts === ClientTurnState.WARLORD_DESTROY_DISTRICT,
      kill: seated && ts === ClientTurnState.ASSASSIN_KILL,
      rob: seated && ts === ClientTurnState.THIEF_ROB,
      putAside,
      chooseChar,
      exchangeHand: seated && ts === ClientTurnState.MAGICIAN_EXCHANGE_HAND,
      discardCards: seated && ts === ClientTurnState.MAGICIAN_DISCARD_CARDS,
      laboratory: seated && ts === ClientTurnState.LABORATORY_DISCARD_CARD,
    };
  }, [gameState, isSpectator, isCurrentPlayerSelf]);

  const showTeamScores = useMemo(() => {
    if (!gameState?.board?.playerOrder) return false;
    return Object.values(gameState.players).some(
      (p) => p.team === TeamId.A || p.team === TeamId.B,
    );
  }, [gameState]);

  const liveTeamScores = useMemo(() => {
    if (!gameState) {
      return {
        A: 0, B: 0, myLabel: 'A', enemyLabel: 'B',
      };
    }
    const { A, B } = computeTeamScores(gameState);
    if (!isSpectator && myTeam === TeamId.B) {
      return {
        A: B, B: A, myLabel: 'B', enemyLabel: 'A',
      };
    }
    return {
      A, B, myLabel: 'A', enemyLabel: 'B',
    };
  }, [gameState, isSpectator, myTeam]);

  const turnOrderChips = useMemo(() => {
    const list = (charactersList?.callable || []) as Array<{ id: number; killed?: boolean; faceUp?: boolean; discardedFaceUp?: boolean }>;
    const current = charactersList?.current || 0;
    if (list.length) {
      return list.map((c, idx) => ({
        idx,
        id: c.id || 0,
        current: c.id === current && current !== 0,
        killed: Boolean(c.killed),
        faceUp: Boolean(c.faceUp || c.discardedFaceUp),
        tip: c.id ? t(`characters.${c.id}.name`) : t('ui.game.character_unknown'),
      }));
    }
    return [1, 2, 3, 4, 5, 6, 7, 8].map((id, idx) => ({
      idx, id, current: id === current, killed: false, faceUp: false, tip: '',
    }));
  }, [charactersList, t]);

  // --- handlers (was Vue methods) ---
  const showEvent = (text: string) => {
    setEventBanner(text);
    if (eventBannerTimer.current) clearTimeout(eventBannerTimer.current);
    eventBannerTimer.current = setTimeout(() => setEventBanner(''), 3500);
  };

  const onCenterCharacterClick = async (ch: { selectable?: boolean; id: number }, index: number) => {
    if (!ch.selectable) return;
    let moveType = MoveType.CHOOSE_CHARACTER;
    let moveData: unknown = index;
    if (modeFlags.kill) {
      moveType = MoveType.ASSASSIN_KILL;
      moveData = ch.id;
    } else if (modeFlags.rob) {
      moveType = MoveType.THIEF_ROB;
      moveData = ch.id;
    }
    try {
      await sendMoveStore({ type: moveType, data: moveData } as Move);
    } catch (e) {
      console.log('character click failed', e);
    }
  };

  const sendMove = async (move: Move, target?: HTMLElement) => {
    if (target && target.blur) target.blur();
    try {
      await sendMoveStore(move);
    } catch (error) {
      console.log('error when sending move', error);
    }
  };

  const toggleAutoplay = async () => {
    if (autoplayBusy) return;
    setAutoplayBusy(true);
    try {
      await setAutoplayStore(!selfIsAutoplay);
    } catch (error) {
      console.error('autoplay toggle failed', error);
    } finally {
      setAutoplayBusy(false);
    }
  };

  const backToLobby = async () => {
    try {
      await leaveRoomStore();
    } catch (e) {
      console.error('leave room failed', e);
    }
    navigate('/');
  };

  const leaveRoom = async () => {
    try {
      await leaveRoomStore();
      navigate('/');
    } catch (e) {
      console.error('leave room failed', e);
    }
  };

  if (!gameState) return null;

  const selfCity = (selfBoard.city || []) as Array<DistrictId | null>;

  return (
    <div className="board-table">
      <div className="board-table__bg" />

      <div className="board-table__top">
        {showTeamScores && (
          <div className="board-table__score-bar">
            <span className="board-table__team-a">
              {isSpectator ? t('ui.team.a') : t('ui.team.mine')} {liveTeamScores.A}
            </span>
            <span className="opacity-50">VS</span>
            <span className="board-table__team-b">
              {isSpectator ? t('ui.team.b') : t('ui.team.enemy')} {liveTeamScores.B}
            </span>
          </div>
        )}
        <TurnOrderBar turnOrderChips={turnOrderChips} gameProgress={gameProgress} />
        <button type="button" className="board-table__leave-btn" onClick={leaveRoom}>
          {t('ui.score.leave_room')}
        </button>
      </div>

      <div className={`board-table__stage${isSpectator ? ' board-table__stage--spectate' : ''}`}>
        {tableSlots.map((slot) => (
          <div key={slot.playerId} className={`board-table__slot board-table__slot--${slot.pos}`}>
            <SeatPanel
              playerId={slot.playerId}
              board={slot.board}
              pickOrder={slot.pickOrder}
              destroyMode={modeFlags.destroy}
              exchangeHandMode={modeFlags.exchangeHand}
              stash={(selfBoard.stash as number) || 0}
              relation={slot.relation}
            />
          </div>
        ))}

        <CenterPanel
          gameProgress={gameProgress}
          charactersList={charactersList || {}}
          gameState={gameState}
          killMode={modeFlags.kill}
          robMode={modeFlags.rob}
          chooseCharacterMode={modeFlags.chooseChar}
          eventBanner={eventBanner}
          onSelectCharacter={onCenterCharacterClick}
        />

        {!isSpectator && (
          <div className="board-table__slot board-table__slot--self">
            <div className="board-table__self-wrap">
              <div className="board-table__self-panel">
                <div className="board-table__self-banner">
                  <span className="board-table__self-pick">{selfPickOrder}</span>
                  <span className="text-truncate flex-fill">{selfName}</span>
                  <span className="board-table__self-vp">⭐ {(selfBoard.score as { total?: number } | undefined)?.total ?? 0}</span>
                  {(selfBoard as { crown?: boolean }).crown && (
                    <span className="seat-panel__crown" title={t('ui.game.crown_holder')}>👑</span>
                  )}
                  <span className="seat-panel__tag">{t('ui.lobby.you')}</span>
                </div>
                <div className="board-table__self-body">
                  <div className="board-table__self-city">
                    {selfCity.map((id, i) => id && <DistrictCard key={`city-${i}`} districtId={id} small />)}
                    {!selfCity.length && <div className="seat-panel__city-empty">{t('ui.game.no_buildings')}</div>}
                  </div>
                  <div className="board-table__self-role">
                    {gameProgress === 'IN_GAME' && selfRoleCard.show && (
                      <CharacterCard
                        characterId={selfRoleCard.id}
                        faceDown={selfRoleCard.faceDown}
                        killed={selfRoleCard.killed}
                        robbed={selfRoleCard.robbed}
                        size="medium"
                      />
                    )}
                  </div>
                </div>
                <div className="board-table__self-hand">
                  <PlayerHand
                    board={selfBoard as Parameters<typeof PlayerHand>[0]['board']}
                    buildMode={modeFlags.build}
                    discardCardsMode={modeFlags.discardCards}
                    laboratoryMode={modeFlags.laboratory}
                  />
                </div>
              </div>
            </div>

            <ActionPanel
              actions={(statusBar.actions ?? []).map((a) => ({
                title: a.title,
                move: a.move,
                args: a.args ? Object.fromEntries(a.args.map((v, i) => [String(i), v])) : undefined,
              }))}
              gameProgress={gameProgress}
              countdownText={countdownText}
              countdownUrgent={countdownUrgent}
              isAutoplay={selfIsAutoplay}
              autoplayBusy={autoplayBusy}
              onAction={sendMove}
              onToggleAutoplay={toggleAutoplay}
            />
          </div>
        )}

        <ActionLog
          displayActionFeed={displayActionFeed as { text: string; kind: string }[]}
          onShowEvent={showEvent}
        />
      </div>

      <EndGameModal
        show={gameProgress === 'FINISHED' && showEndModal}
        gameState={gameState}
        selfId={self}
        isSpectator={isSpectator}
        showTeamScores={showTeamScores}
        getPlayerFromId={getPlayer}
        onClose={() => setShowEndModal(false)}
        onLeave={backToLobby}
      />

      {gameProgress === 'FINISHED' && !showEndModal && (
        <div className="board-table__end-bar">
          <button type="button" className="btn btn-sm btn-warning mr-2" onClick={() => setShowEndModal(true)}>
            {t('ui.score.show_result')}
          </button>
          <button type="button" className="btn btn-sm btn-outline-light" onClick={backToLobby}>
            {t('ui.score.leave_room')}
          </button>
        </div>
      )}
    </div>
  );
}
