// client/src/components/game/EndGameModal.vue
<template>
  <div
    v-if="show"
    class="modal fade show d-block"
    style="background:rgba(0,0,0,0.65); z-index: 1050;"
  >
    <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header" :class="endHeaderClass">
          <h4 class="modal-title mb-0">{{ endTitle }}</h4>
          <button
            type="button"
            class="close text-white"
            @click="$emit('close')"
            aria-label="close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="text-center mb-3">
            <div class="h5">{{ endSubtitle }}</div>
            <div v-if="showTeamScores" class="mt-2">
              <span class="badge badge-primary badge-pill px-3 py-2 mr-2">
                {{ isSpectator ? $t('ui.team.a') : $t('ui.team.mine') }} {{ liveTeamScores.A }}
              </span>
              <span class="badge badge-danger badge-pill px-3 py-2">
                {{ isSpectator ? $t('ui.team.b') : $t('ui.team.enemy') }} {{ liveTeamScores.B }}
              </span>
            </div>
          </div>
          <table class="table table-sm table-striped mb-0">
            <thead>
              <tr>
                <th>{{ $t('ui.lobby.players') }}</th>
                <th v-if="showTeamScores">{{ $t('ui.stats.team') }}</th>
                <th class="text-right">{{ $t('ui.score.total') }}</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="row in endScoreRows" :key="row.id">
                <td>
                  {{ row.name }}
                   <span
                     v-if="row.isSelf"
                     class="badge badge-info ml-1"
                  >{{ $t('ui.lobby.you') }}</span>
                  <span v-if="row.isAi" class="badge badge-dark ml-1">AI</span>
                </td>
                <td v-if="showTeamScores">
                  <span class="badge" :class="row.team === 'A' ? 'badge-primary' : 'badge-danger'">
                    {{ row.team }}
                  </span>
                </td>
                <td class="text-right font-weight-bold">{{ row.total }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" @click="$emit('close')">
            {{ $t('ui.score.keep_browsing') }}
          </button>
          <button type="button" class="btn btn-primary" @click="$emit('leave')">
            {{ $t('ui.score.leave_room') }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { computeTeamScores, MatchResult, TeamId } from 'citadels-common';

export default defineComponent({
  name: 'EndGameModal',
  props: {
    show: {
      type: Boolean,
      required: true,
    },
    gameState: {
      type: Object,
      required: true,
    },
    selfId: {
      type: String,
      required: true,
    },
    isSpectator: {
      type: Boolean,
      required: true,
    },
    showTeamScores: {
      type: Boolean,
      required: true,
    },
    getPlayerFromId: {
      type: Function,
      required: true,
    },
  },
  emits: ['close', 'leave'],
  computed: {
    isWin() {
      const result = this.gameState?.matchResult;
      const team = this.getPlayerFromId(this.selfId)?.team;
      return (result === MatchResult.TEAM_A_WIN && team === TeamId.A)
        || (result === MatchResult.TEAM_B_WIN && team === TeamId.B);
    },
    isLose() {
      const result = this.gameState?.matchResult;
      const team = this.getPlayerFromId(this.selfId)?.team;
      return (result === MatchResult.TEAM_A_WIN && team === TeamId.B)
        || (result === MatchResult.TEAM_B_WIN && team === TeamId.A);
    },
    endTitle() {
      if (this.isSpectator) return this.$t('ui.score.game_over');
      if (this.isWin) return this.$t('ui.score.you_win');
      if (this.isLose) return this.$t('ui.score.you_lose');
      if (this.gameState?.matchResult === MatchResult.DRAW) return this.$t('ui.score.draw');
      return this.$t('ui.score.game_over');
    },
    endSubtitle() {
      if (this.matchSummary?.detail) return this.matchSummary.detail;
      if (this.matchSummary?.title) return this.matchSummary.title;
      return '';
    },
    endHeaderClass() {
      if (this.isWin) return 'bg-success text-white';
      if (this.isLose) return 'bg-danger text-white';
      return 'bg-secondary text-white';
    },
    liveTeamScores() {
      if (!this.gameState) return { A: 0, B: 0 };
      const { A, B } = computeTeamScores(this.gameState);
      const mine = this.getPlayerFromId(this.selfId)?.team;
      if (!this.isSpectator && mine === TeamId.B) {
        return { A: B, B: A };
      }
      return { A, B };
    },
    matchSummary() {
      if (!this.showTeamScores) return null;
      const { A, B } = this.liveTeamScores;
      const result = this.gameState?.matchResult;
      let title = this.$t('ui.score.draw');
      if (result === MatchResult.TEAM_A_WIN) title = this.$t('ui.score.team_a_win');
      if (result === MatchResult.TEAM_B_WIN) title = this.$t('ui.score.team_b_win');
      if (result === MatchResult.CASUAL_END) title = this.$t('ui.score.game_over');
      return {
        title,
        detail: this.$t('ui.score.team_totals', { a: A, b: B }),
      };
    },
    endScoreRows() {
      const order = this.gameState?.board?.playerOrder || [];
      return order.map((pid: string) => {
        const meta = this.getPlayerFromId(pid);
         const board = this.gameState?.board?.players?.[pid];
        let team = '';
        if (meta?.team === TeamId.A) team = 'A';
        if (meta?.team === TeamId.B) team = 'B';
        return {
          id: pid,
          name: meta?.username || pid,
          isSelf: pid === this.selfId,
          isAi: Boolean(meta?.isAi),
          team,
          total: board?.score?.total ?? 0,
        };
      }).sort((a: any, b: any) => b.total - a.total);
    },
  },
});
</script>

// client-react/src/components/game/EndGameModal.tsx
import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { createPortal } from 'react-dom';
import {
  computeTeamScores, MatchResult, TeamId, ClientGameState, PlayerId,
} from 'citadels-common';

// Player meta is an inline type inside ClientGameState['players']; extract it
// rather than inventing a name that common doesn't export.
type PlayerMeta = ClientGameState['players'][PlayerId];

interface EndScoreRow {
  id: string;
  name: string;
  isSelf: boolean;
  isAi: boolean;
  team: string;
  total: number;
}

interface EndGameModalProps {
  show: boolean;
  gameState: ClientGameState;
  selfId: PlayerId;
  isSpectator: boolean;
  showTeamScores: boolean;
  getPlayerFromId: (id: PlayerId) => PlayerMeta | undefined;
  onClose?: () => void;
  onLeave?: () => void;
}

// Mirrors Vue EndGameModal.vue. Uses createPortal (same as Modal) rather than
// the shared Modal component because this dialog has a bespoke table body.
// getPlayerFromId is passed as a prop (parent already has the selector) to
// avoid a store dependency inside this presentational component.
export default function EndGameModal({
  show,
  gameState,
  selfId,
  isSpectator,
  showTeamScores,
  getPlayerFromId,
  onClose,
  onLeave,
}: EndGameModalProps) {
  const { t } = useTranslation();

  const { isWin, isLose } = useMemo(() => {
    const result = gameState?.matchResult;
    const team = getPlayerFromId(selfId)?.team;
    return {
      isWin: (result === MatchResult.TEAM_A_WIN && team === TeamId.A)
        || (result === MatchResult.TEAM_B_WIN && team === TeamId.B),
      isLose: (result === MatchResult.TEAM_A_WIN && team === TeamId.B)
        || (result === MatchResult.TEAM_B_WIN && team === TeamId.A),
    };
  }, [gameState, selfId, getPlayerFromId]);

  const liveTeamScores = useMemo(() => {
    if (!gameState) return { A: 0, B: 0 };
    const { A, B } = computeTeamScores(gameState);
    const mine = getPlayerFromId(selfId)?.team;
    if (!isSpectator && mine === TeamId.B) {
      return { A: B, B: A };
    }
    return { A, B };
  }, [gameState, selfId, isSpectator, getPlayerFromId]);

  const endTitle = useMemo(() => {
    if (isSpectator) return t('ui.score.game_over');
    if (isWin) return t('ui.score.you_win');
    if (isLose) return t('ui.score.you_lose');
    if (gameState?.matchResult === MatchResult.DRAW) return t('ui.score.draw');
    return t('ui.score.game_over');
  }, [isSpectator, isWin, isLose, gameState, t]);

  const matchSummary = useMemo(() => {
    if (!showTeamScores) return null;
    const { A, B } = liveTeamScores;
    const result = gameState?.matchResult;
    let title = t('ui.score.draw');
    if (result === MatchResult.TEAM_A_WIN) title = t('ui.score.team_a_win');
    if (result === MatchResult.TEAM_B_WIN) title = t('ui.score.team_b_win');
    if (result === MatchResult.CASUAL_END) title = t('ui.score.game_over');
    return {
      title,
      detail: t('ui.score.team_totals', { a: A, b: B }),
    };
  }, [showTeamScores, liveTeamScores, gameState, t]);

  const endSubtitle = matchSummary?.detail || matchSummary?.title || '';
  const endHeaderClass = isWin ? 'bg-success text-white'
    : isLose ? 'bg-danger text-white'
    : 'bg-secondary text-white';

  const endScoreRows = useMemo<EndScoreRow[]>(() => {
    const order = gameState?.board?.playerOrder || [];
    return order.map((pid) => {
      const meta = getPlayerFromId(pid);
      const board = gameState?.board?.players?.[pid];
      let team = '';
      if (meta?.team === TeamId.A) team = 'A';
      if (meta?.team === TeamId.B) team = 'B';
      return {
        id: pid,
        name: meta?.username || pid,
        isSelf: pid === selfId,
        isAi: Boolean(meta?.isAi),
        team,
        total: board?.score?.total ?? 0,
      };
    }).sort((a, b) => b.total - a.total);
  }, [gameState, selfId, getPlayerFromId]);

  if (!show) return null;

  return createPortal(
    <div className="modal fade show d-block" style={{ background: 'rgba(0,0,0,0.65)', zIndex: 1050 }}>
      <div className="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
        <div className="modal-content">
          <div className={`modal-header ${endHeaderClass}`}>
            <h4 className="modal-title mb-0">{endTitle}</h4>
            <button type="button" className="close text-white" onClick={onClose} aria-label="close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div className="modal-body">
            <div className="text-center mb-3">
              <div className="h5">{endSubtitle}</div>
              {showTeamScores && (
                <div className="mt-2">
                  <span className="badge badge-primary badge-pill px-3 py-2 mr-2">
                    {isSpectator ? t('ui.team.a') : t('ui.team.mine')} {liveTeamScores.A}
                  </span>
                  <span className="badge badge-danger badge-pill px-3 py-2">
                    {isSpectator ? t('ui.team.b') : t('ui.team.enemy')} {liveTeamScores.B}
                  </span>
                </div>
              )}
            </div>
            <table className="table table-sm table-striped mb-0">
              <thead>
                <tr>
                  <th>{t('ui.lobby.players')}</th>
                  {showTeamScores && <th>{t('ui.stats.team')}</th>}
                  <th className="text-right">{t('ui.score.total')}</th>
                </tr>
              </thead>
              <tbody>
                {endScoreRows.map((row) => (
                  <tr key={row.id}>
                    <td>
                      {row.name}
                      {row.isSelf && <span className="badge badge-info ml-1">{t('ui.lobby.you')}</span>}
                      {row.isAi && <span className="badge badge-dark ml-1">AI</span>}
                    </td>
                    {showTeamScores && (
                      <td>
                        <span className={`badge ${row.team === 'A' ? 'badge-primary' : 'badge-danger'}`}>
                          {row.team}
                        </span>
                      </td>
                    )}
                    <td className="text-right font-weight-bold">{row.total}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="modal-footer">
            <button type="button" className="btn btn-outline-secondary" onClick={onClose}>
              {t('ui.score.keep_browsing')}
            </button>
            <button type="button" className="btn btn-primary" onClick={onLeave}>
              {t('ui.score.leave_room')}
            </button>
          </div>
        </div>
      </div>
    </div>,
    document.body,
  );
}
