// client/src/components/game/GameScreen.vue
<template>
  <div class="container-fluid p-0 h-100 game-screen">
    <div v-if="showLobby" class="container-lg h-100 py-4">
      <LobbyScreen />
    </div>
    <div v-else-if="showBoard" class="h-100 d-flex">
      <BoardScreen />
    </div>
    <div v-else class="h-100">
      Invalid game state: {{ gameProgress }}
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { mapGetters } from 'vuex';
import BoardScreen from './BoardScreen.vue';
import LobbyScreen from './LobbyScreen.vue';

export default defineComponent({
  components: { LobbyScreen, BoardScreen },
  name: 'GameScreen',
  computed: {
    ...mapGetters([
      'gameProgress',
    ]),
    showLobby() {
      return this.gameProgress === 'IN_LOBBY';
    },
    showBoard() {
      return this.gameProgress === 'IN_GAME' || this.gameProgress === 'FINISHED';
    },
  },
});
</script>

<style scoped>
.game-screen {
  min-height: 0;
}
</style>

// client-react/src/components/game/GameScreen.tsx
import { useGameProgress } from '@/store';
import BoardScreen from './BoardScreen';
import LobbyScreen from './LobbyScreen';

// Mirrors Vue GameScreen.vue. Simple switch on gameProgress: IN_LOBBY →
// LobbyScreen; IN_GAME/FINISHED → BoardScreen; anything else → error msg.
export default function GameScreen() {
  const gameProgress = useGameProgress();

  const showLobby = gameProgress === 'IN_LOBBY';
  const showBoard = gameProgress === 'IN_GAME' || gameProgress === 'FINISHED';

  return (
    <div className="container-fluid p-0 h-100 game-screen">
      {showLobby && (
        <div className="container-lg h-100 py-4">
          <LobbyScreen />
        </div>
      )}
      {showBoard && (
        <div className="h-100 d-flex">
          <BoardScreen />
        </div>
      )}
      {!showLobby && !showBoard && (
        <div className="h-100">
          Invalid game state: {gameProgress}
        </div>
      )}
    </div>
  );
}
