// client/src/components/game/TurnOrderBar.vue
<template>
  <div v-if="gameProgress === 'IN_GAME'" class="board-table__turn-order">
    <span class="board-table__turn-label">{{ $t('ui.game.turn_order') }}</span>
    <span
      v-for="ch in turnOrderChips"
      :key="ch.id + '-' + ch.idx"
      class="board-table__char-chip"
      :class="[
        `board-table__char-chip--c${ch.id || 0}`,
        {
          'board-table__char-chip--current': ch.current,
          'board-table__char-chip--killed': ch.killed,
          'board-table__char-chip--face-up': ch.faceUp,
        },
      ]"
      :title="ch.tip"
    >{{ ch.id || '?' }}</span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { GameProgress } from 'citadels-common';

export default defineComponent({
  name: 'TurnOrderBar',
  props: {
    turnOrderChips: {
      type: Array,
      required: true,
    },
    gameProgress: {
      type: String,
      required: true,
    },
  },
});
</script>

// client-react/src/components/game/TurnOrderBar.tsx
import { useTranslation } from 'react-i18next';

export interface TurnOrderChip {
  id: number;
  idx: number;
  current: boolean;
  killed: boolean;
  faceUp: boolean;
  tip: string;
}

interface TurnOrderBarProps {
  turnOrderChips: TurnOrderChip[];
  gameProgress: string;
}

// Pure presentational — mirrors Vue TurnOrderBar.vue. Only renders during
// IN_GAME (parent passes gameProgress).
export default function TurnOrderBar({ turnOrderChips, gameProgress }: TurnOrderBarProps) {
  const { t } = useTranslation();
  if (gameProgress !== 'IN_GAME') return null;
  return (
    <div className="board-table__turn-order">
      <span className="board-table__turn-label">{t('ui.game.turn_order')}</span>
      {turnOrderChips.map((ch) => (
        <span
          key={`${ch.id}-${ch.idx}`}
          className={`board-table__char-chip board-table__char-chip--c${ch.id || 0}${ch.current ? ' board-table__char-chip--current' : ''}${ch.killed ? ' board-table__char-chip--killed' : ''}${ch.faceUp ? ' board-table__char-chip--face-up' : ''}`}
          title={ch.tip}
        >
          {ch.id || '?'}
        </span>
      ))}
    </div>
  );
}
