// client-react/src/components/game/elements/PlayerHand.tsx
import { useEffect, useState } from 'react';
import {
  Move, MoveType, DistrictId, PlayerBoard, districts,
} from 'citadels-common';
import Emoji from '@/components/common/Emoji';
import { useAppStore } from '@/store';
import DistrictCard from './DistrictCard';

type BoardWithCrown = PlayerBoard & { crown: boolean };

interface PlayerHandProps {
  board: BoardWithCrown;
  buildMode?: boolean;
  discardCardsMode?: boolean;
  laboratoryMode?: boolean;
}

// Mirrors Vue elements/PlayerHand.vue. The Vue `data().selectedCards` + two
// deep watchers (board.hand change resets; selectedCards change commits to
// store + triggers build/lab move) become a useState + useEffect pair.
export default function PlayerHand({
  board,
  buildMode = false,
  discardCardsMode = false,
  laboratoryMode = false,
}: PlayerHandProps) {
  const sendMove = useAppStore((s) => s.sendMove);
  const setSelectedCards = useAppStore((s) => s.setSelectedCards);

  const [selectedCards, setSelected] = useState<boolean[]>([]);

  const showTmpHand = board.tmpHand.length > 0;

  // Reset selection when hand changes (mirrors Vue watch board.hand).
  useEffect(() => {
    setSelected([]);
  }, [board.hand]);

  // Commit selection to store + trigger build/lab move when a card is picked
  // (mirrors Vue watch selectedCards).
  useEffect(() => {
    const cards: DistrictId[] = [];
    selectedCards.forEach((isSelected, index) => {
      if (isSelected) {
        const card = board.hand[index];
        if (card) cards.push(card);
      }
    });
    setSelectedCards(cards);

    if (cards.length > 0) {
      if (buildMode) {
        const move: Move = { type: MoveType.BUILD_DISTRICT, data: cards[0] };
        sendMove(move).catch((e) => console.log('error when sending move', e));
        setSelected([]);
      } else if (laboratoryMode) {
        const move: Move = { type: MoveType.LABORATORY_DISCARD_CARD, data: cards[0] };
        sendMove(move).catch((e) => console.log('error when sending move', e));
        setSelected([]);
      }
    }
    // discardCardsMode just toggles selectedCards state without a move;
    // the parent reads selectedCards from the store for the discard confirm.
  }, [selectedCards, buildMode, laboratoryMode, board.hand, sendMove, setSelectedCards]);

  const canBuild = (name: DistrictId): boolean => {
    if (!buildMode) return false;
    const data = districts[name as keyof typeof districts] as { cost?: number } | undefined;
    return !board.city.includes(name) && (data?.cost ?? 0) <= board.stash;
  };

  const chooseCard = async (name: DistrictId) => {
    try {
      const move: Move = { type: MoveType.DRAW_CARDS, data: name };
      await sendMove(move);
    } catch (error) {
      console.log('error when sending move', error);
    }
  };

  const handleSelect = (index: number, next: boolean) => {
    setSelected((prev) => {
      const copy = [...prev];
      copy[index] = next;
      return copy;
    });
  };

  return (
    <div className="d-flex justify-content-start align-items-end overflow-auto">
      {board.crown && (
        <div className="crown card rounded-pill bg-danger p-3 m-2 shadow-sm">
          <Emoji emoji="👑" />
        </div>
      )}
      <div className="flex-grow-1 px-2 pb-2 d-flex overflow-hidden">
        {board.hand.map((id, i) => id && (
          <div key={i} className="district-card-wrapper pt-3">
            <div className="district-card">
              <DistrictCard
                districtId={id}
                disabled={showTmpHand || (buildMode && !canBuild(id))}
                selectable={canBuild(id) || discardCardsMode || laboratoryMode}
                selected={selectedCards[i]}
                onSelect={(next) => handleSelect(i, next)}
              />
            </div>
          </div>
        ))}
      </div>
      {showTmpHand && (
        <div className="bg-secondary d-flex justify-content-start pl-2 py-2 my-n2">
          {board.tmpHand.map((id, i) => id && (
            <DistrictCard
              key={i}
              districtId={id}
              className="mr-2"
              selectable={showTmpHand}
              onSelect={() => chooseCard(id)}
            />
          ))}
        </div>
      )}
      <div
        className="stash d-flex flex-column-reverse flex-wrap-reverse justify-content-start"
        style={{ width: `${2.5 * Math.ceil(board.stash / 5)}rem` }}
      >
        {Array.from({ length: board.stash }, (_, i) => (
          <Emoji key={i} emoji="🪙" />
        ))}
      </div>
    </div>
  );
}

// client/src/components/game/elements/PlayerHand.vue
<template>
<div class="d-flex justify-content-start align-items-end overflow-auto">
  <div v-if="board.crown" class="crown card rounded-pill bg-danger p-3 m-2 shadow-sm">
    <emoji emoji="👑"></emoji>
  </div>
  <div class="flex-grow-1 px-2 pb-2 d-flex overflow-hidden">
    <div
      class="district-card-wrapper pt-3"
      v-for="id, i in board.hand"
      :key="i"
    >
      <div class="district-card">
        <DistrictCard
          :district-id="id"
          :disabled="showTmpHand || (buildMode && !canBuild(id))"
          :selectable="canBuild(id) || discardCardsMode || laboratoryMode"
          v-model:selected="selectedCards[i]"
        />
      </div>
    </div>
  </div>
  <div
    v-if="showTmpHand"
    class="bg-secondary d-flex justify-content-start pl-2 py-2 my-n2"
  >
    <DistrictCard
      v-for="id, i in board.tmpHand"
      :key="i"
      :district-id="id"
      class="mr-2"
      @click="chooseCard(id)"
      :selectable="showTmpHand"
    />
  </div>
  <div
    class="stash d-flex flex-column-reverse flex-wrap-reverse justify-content-start"
    :style="`width: ${2.5 * Math.ceil(board.stash / 5)}rem;`"
  >
    <emoji v-for="i in board.stash" :key="i" class="coin" emoji="🪙"></emoji>
  </div>
</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Move, MoveType, DistrictId, PlayerBoard } from 'citadels-common';
import { store } from '../../../store';
import DistrictCard from './DistrictCard.vue';

type BoardWithCrown = PlayerBoard & { crown: boolean };

export default defineComponent({
  name: 'PlayerHand',
  components: {
    DistrictCard,
  },
  props: {
    board: {
      type: Object as () => BoardWithCrown,
      required: true,
    },
    buildMode: {
      type: Boolean,
      default: false,
    },
    discardCardsMode: {
      type: Boolean,
      default: false,
    },
    laboratoryMode: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      selectedCards: [] as boolean[],
    };
  },
  computed: {
    showTmpHand() {
      return this.board.tmpHand.length > 0;
    },
  },
  methods: {
    canBuild(name: DistrictId): boolean {
      if (!this.buildMode) return false;
      return !this.board.city.includes(name)
        && store.getters.getDistrictFromId(name).cost <= this.board.stash;
    },
    async chooseCard(name: DistrictId) {
      try {
        const move: Move = { type: MoveType.DRAW_CARDS, data: name };
        await store.dispatch('sendMove', move);
      } catch (error) {
        console.log('error when sending move', error);
      }
    },
    async chooseCardBuild(name: DistrictId) {
      if (!this.canBuild(name)) return;

      try {
        const move: Move = { type: MoveType.BUILD_DISTRICT, data: name };
        await store.dispatch('sendMove', move);
      } catch (error) {
        console.log('error when sending move', error);
      }
    },
    async chooseCardLaboratory(name: DistrictId) {
      try {
        const move: Move = { type: MoveType.LABORATORY_DISCARD_CARD, data: name };
        await store.dispatch('sendMove', move);
      } catch (error) {
        console.log('error when sending move', error);
      }
    },
  },
  watch: {
    board: {
      handler(newBoard, oldBoard) {
        if (newBoard.hand !== oldBoard.hand) {
          this.selectedCards = [];
        }
      },
      deep: true,
    },
    selectedCards: {
      handler(val: boolean[]) {
        const cards: DistrictId[] = [];
        val.forEach((isSelected: boolean, index: number) => {
          if (isSelected) {
            const card = this.board.hand[index];
            if (card !== undefined && card !== null) cards.push(card);
          }
        });

        store.commit('setSelectedCards', { cards });

        if (cards.length > 0) {
          if (this.buildMode) {
            this.chooseCardBuild(cards[0]);
            this.selectedCards = [];
          } else if (this.laboratoryMode) {
            this.chooseCardLaboratory(cards[0]);
            this.selectedCards = [];
          }
        }
      },
      deep: true,
    },
  },
});
</script>

<style lang="scss" scoped>
.stash {
  height: 9em;
  margin-top: 2.5em;
}

.coin {
  font-size: 2em;
  height: .8em;
  position: relative;
  bottom: .8em;
  filter: drop-shadow(0 -1px 2px rgba(0, 0, 0, .5));
}

.crown {
  font-size: 2em;
  min-width: 2.5em;
  text-align: center;
}

.district-card-wrapper {
  width: 20px;
  flex: 1;
  max-width: 7.5rem;

  &:hover {
    width: 100%;

    .district-card {
      transform: translatey(-0.35rem);
    }
  }

  &:hover ~ .card {
    z-index: 1;
  }

  &:last-child {
    width: auto;
  }

  .district-card {
    transition: transform .1s linear;
    margin: auto;
    box-sizing: border-box;
  }
}
</style>
