// client-react/src/components/game/elements/PlayerCity.tsx
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Move, MoveType, DistrictId, TeamId, PlayerBoard,
} from 'citadels-common';
import CharactersList from './CharactersList';
import DistrictCard from './DistrictCard';
import PlayerScore from './PlayerScore';
import Modal from '@/components/common/Modal';
import Emoji from '@/components/common/Emoji';
import { cn } from '@/utils/cn';
import {
  useAppStore,
  useGameProgress,
  useCurrentPlayerId,
  selectPlayerFromId,
  selectDistrictDestroyPrice,
  selectPlayerPosition,
} from '@/store';

type BoardWithCrown = PlayerBoard & { crown: boolean };

interface PlayerCityProps {
  playerId: string;
  board: BoardWithCrown;
  destroyMode?: boolean;
  exchangeHandMode?: boolean;
  stash?: number;
}

// Mirrors Vue elements/PlayerCity.vue. mapGetters → useAppStore hooks +
// pure selectors operating on gameState. The pendingDestroy data field →
// useState. AppModal → Modal with children/footer props.
export default function PlayerCity({
  playerId,
  board,
  destroyMode = false,
  exchangeHandMode = false,
  stash = 0,
}: PlayerCityProps) {
  const { t } = useTranslation();
  const gameState = useAppStore((s) => s.gameState);
  const sendMove = useAppStore((s) => s.sendMove);
  const gameProgress = useGameProgress();
  const currentPlayerId = useCurrentPlayerId();

  const [pendingDestroy, setPendingDestroy] = useState<DistrictId | null>(null);

  const getPlayer = selectPlayerFromId(gameState);
  const player = getPlayer(playerId);
  const username = player?.username;
  const isCurrentPlayer = currentPlayerId === playerId;

  const teamClass = (() => {
    const team = player?.team;
    if (team === TeamId.A) return 'A';
    if (team === TeamId.B) return 'B';
    return '';
  })();

  const playerKillRobLabel = (() => {
    // board.characters is typed as { id }[] in common, but at runtime carries
    // killed/robbed flags set by the engine. Cast to access them.
    const chars = (board?.characters || []) as Array<{ id: number; killed?: boolean; robbed?: boolean }>;
    const hit = chars.find((c) => c.killed || c.robbed);
    if (!hit || !hit.id) return null;
    return {
      killed: Boolean(hit.killed),
      robbed: Boolean(hit.robbed),
      name: t(`characters.${hit.id}.name`),
    };
  })();

  const getDestroyPrice = selectDistrictDestroyPrice(gameState);
  const canDestroy = (name: DistrictId): boolean => {
    if (!destroyMode) return false;
    const cost = getDestroyPrice(playerId, name);
    return cost >= 0 && cost <= stash;
  };

  const getPlayerPos = selectPlayerPosition(gameState);
  const sendDestroyMove = async (name: DistrictId) => {
    try {
      const move: Move = {
        type: MoveType.WARLORD_DESTROY_DISTRICT,
        data: {
          player: getPlayerPos(playerId),
          card: name,
        },
      };
      await sendMove(move);
    } catch (error) {
      console.log('error when sending move', error);
    }
  };

  const chooseCardDestroy = (name: DistrictId) => {
    if (!canDestroy(name)) return;
    const selfId = gameState?.self;
    const myTeam = selfId ? getPlayer(selfId)?.team : undefined;
    const theirTeam = player?.team;
    if (myTeam != null && theirTeam != null && myTeam === theirTeam) {
      setPendingDestroy(name);
      return;
    }
    sendDestroyMove(name);
  };

  const exchangeHand = async () => {
    if (!exchangeHandMode) return;
    try {
      const move: Move = {
        type: MoveType.MAGICIAN_EXCHANGE_HAND,
        data: getPlayerPos(playerId),
      };
      await sendMove(move);
    } catch (error) {
      console.log('error when sending move', error);
    }
  };

  return (
    <div className="w-100 card bg-secondary shadow-sm" style={{ minWidth: '9em' }}>
      <div className="p-1 text-light d-flex flex-column">
        <div className="bg-dark p-1 flex-fill rounded d-flex flex-column">
          <h5>
            <span className={cn('badge w-100', {
              'bg-primary': isCurrentPlayer && !teamClass,
              'bg-info': !isCurrentPlayer && teamClass === 'A',
              'bg-danger': !isCurrentPlayer && teamClass === 'B',
              'bg-primary border border-light': isCurrentPlayer && teamClass === 'A',
              'bg-danger border border-light': isCurrentPlayer && teamClass === 'B',
            })}>
              {username}
              {teamClass && <span className="small">({teamClass})</span>}
            </span>
          </h5>
          <p className="text-center">
            {board.crown && (
              <span className="badge badge-pill badge-danger p-2 mr-2"><Emoji emoji="👑" /></span>
            )}
            <span className="badge badge-pill badge-secondary p-2 mr-2">
              {board.stash} <Emoji emoji="🪙" />
            </span>
            <span
              className={cn('badge badge-pill p-2', {
                'badge-secondary': !exchangeHandMode,
                'badge-primary cursor-pointer': exchangeHandMode,
              })}
              onClick={exchangeHand}
              title={exchangeHandMode ? t('ui.game.actions.choose_hand') : ''}
            >
              {board.hand.length} <Emoji emoji="🃏" />
            </span>
            <span className="badge badge-pill badge-warning p-2 ml-2" title="实时总分">
              {board.score?.total ?? 0} 分
            </span>
          </p>
          {gameProgress === 'IN_GAME' && <CharactersList characters={board.characters} />}
          {playerKillRobLabel && (
            <div className="text-center small mt-1">
              {playerKillRobLabel.killed ? (
                <span className="badge badge-danger">💀 {playerKillRobLabel.name}</span>
              ) : playerKillRobLabel.robbed ? (
                <span className="badge badge-warning text-dark">💰 {playerKillRobLabel.name}</span>
              ) : null}
            </div>
          )}
        </div>
      </div>
      <div className="p-2 bg-secondary d-flex justify-content-center flex-wrap overflow-auto gap-2">
        {board.city.map((id, i) => (
          <DistrictCard
            key={i}
            districtId={id}
            disabled={destroyMode && !canDestroy(id)}
            selectable={canDestroy(id)}
            small
            onSelect={() => chooseCardDestroy(id)}
          />
        ))}
      </div>
      <div className="flex-fill" />
      <PlayerScore score={board.score} />

      <Modal
        show={pendingDestroy !== null}
        title={t('ui.game.destroy_confirm_title')}
        headerClass="bg-warning text-white"
        onClose={() => setPendingDestroy(null)}
        footer={(
          <>
            <button type="button" className="btn btn-secondary" onClick={() => setPendingDestroy(null)}>
              {t('ui.cancel')}
            </button>
            <button
              type="button"
              className="btn btn-danger"
              onClick={() => {
                if (pendingDestroy !== null) {
                  sendDestroyMove(pendingDestroy);
                  setPendingDestroy(null);
                }
              }}
            >
              {t('ui.confirm')}
            </button>
          </>
        )}
      >
        <p>{t('ui.game.warn_destroy_ally', { name: username })}</p>
      </Modal>
    </div>
  );
}

// client/src/components/game/elements/PlayerCity.vue
<template>
  <div class="w-100 card bg-secondary shadow-sm" style="min-width: 9em;">
    <div class="p-1 text-light d-flex flex-column">
      <div class="bg-dark p-1 flex-fill rounded d-flex flex-column">
        <h5>
          <span
            class="badge w-100"
            :class="{
              'bg-primary': isCurrentPlayer && !teamClass,
              'bg-info': !isCurrentPlayer && teamClass === 'A',
              'bg-danger': !isCurrentPlayer && teamClass === 'B',
              'bg-primary border border-light': isCurrentPlayer && teamClass === 'A',
              'bg-danger border border-light': isCurrentPlayer && teamClass === 'B',
            }"
          >
            {{ username }}
            <span v-if="teamClass" class="small">({{ teamClass }})</span>
          </span>
        </h5>
        <p class="text-center">
          <span v-if="board.crown" class="badge badge-pill badge-danger p-2 mr-2">
            <emoji emoji="👑"></emoji>
          </span>
          <span class="badge badge-pill badge-secondary p-2 mr-2">
            {{ board.stash }} <emoji emoji="🪙"></emoji>
          </span>
          <span
            class="badge badge-pill p-2"
            :class="{
              'badge-secondary': !exchangeHandMode,
              'badge-primary cursor-pointer': exchangeHandMode,
            }"
            @click="exchangeHand()"
             :title="exchangeHandMode ? $t('ui.game.actions.choose_hand') : ''"
          >{{ board.hand.length }} <emoji emoji="🃏"></emoji></span>
          <span class="badge badge-pill badge-warning p-2 ml-2" title="实时总分">
            {{ board.score?.total ?? 0 }} 分
          </span>
        </p>
        <CharactersList v-if="gameProgress === 'IN_GAME'" :characters="board.characters" />
        <!-- killed/robbed badge even if character chip still resolving -->
        <div
          v-if="playerKillRobLabel"
          class="text-center small mt-1"
        >
          <span
            v-if="playerKillRobLabel.killed"
            class="badge badge-danger"
          >💀 {{ playerKillRobLabel.name }}</span>
          <span
            v-else-if="playerKillRobLabel.robbed"
            class="badge badge-warning text-dark"
          >💰 {{ playerKillRobLabel.name }}</span>
        </div>
      </div>
    </div>
    <div class="p-2 bg-secondary d-flex justify-content-center flex-wrap overflow-auto gap-2">
      <DistrictCard
        v-for="id, i in board.city"
        :key="i"
        :district-id="id"
        @click="chooseCardDestroy(id)"
        :disabled="destroyMode && !canDestroy(id)"
        :selectable="canDestroy(id)"
        small
      />
    </div>
    <div class="flex-fill"></div>
    <PlayerScore :score="board.score" />

    <AppModal
      :show="pendingDestroy !== null"
      :title="$t('ui.game.destroy_confirm_title')"
      header-class="bg-warning text-white"
      @close="cancelDestroy"
    >
      <p>{{ $t('ui.game.warn_destroy_ally', { name: username }) }}</p>
      <template #footer>
        <button
          type="button"
          class="btn btn-secondary"
          @click="cancelDestroy"
        >{{ $t('ui.cancel') }}</button>
        <button
          type="button"
          class="btn btn-danger"
          @click="confirmDestroy"
        >{{ $t('ui.confirm') }}</button>
      </template>
    </AppModal>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { mapGetters } from 'vuex';
import {
  Move, MoveType, DistrictId, TeamId, PlayerBoard,
} from 'citadels-common';
import { store } from '../../../store';
import CharactersList from './CharactersList.vue';
import DistrictCard from './DistrictCard.vue';
import PlayerScore from './PlayerScore.vue';
import AppModal from '../../common/Modal.vue';

type BoardWithCrown = PlayerBoard & { crown: boolean };

export default defineComponent({
  name: 'PlayerCity',
  components: {
    DistrictCard,
    CharactersList,
    PlayerScore,
    AppModal,
  },
  props: {
    playerId: {
      type: String,
      required: true,
    },
    board: {
      type: Object as () => BoardWithCrown,
      required: true,
    },
    destroyMode: {
      type: Boolean,
      default: false,
    },
    exchangeHandMode: {
      type: Boolean,
      default: false,
    },
    stash: {
      type: Number,
      default: 0,
    },
  },
  data() {
    return {
      pendingDestroy: null as DistrictId | null,
    };
  },
  computed: {
    ...mapGetters([
      'getPlayerFromId',
      'gameProgress',
      'currentPlayerId',
    ]),
    username() {
      return this.getPlayerFromId(this.playerId)?.username;
    },
    isCurrentPlayer() {
      return this.currentPlayerId === this.playerId;
    },
    teamClass() {
      const team = this.getPlayerFromId(this.playerId)?.team;
      if (team === TeamId.A) return 'A';
      if (team === TeamId.B) return 'B';
      return '';
    },
    /** show kill/rob as soon as assassin/thief acts (not only when that role's turn arrives) */
    playerKillRobLabel() {
      const chars = this.board?.characters || [];
      const hit = chars.find((c: any) => c.killed || c.robbed);
      if (!hit || !hit.id) return null;
      return {
        killed: Boolean(hit.killed),
        robbed: Boolean(hit.robbed),
        name: this.$t(`characters.${hit.id}.name`),
      };
    },
  },
  methods: {
    canDestroy(name: DistrictId): boolean {
      if (!this.destroyMode) return false;
      const cost = store.getters.getDistrictDestroyPrice(this.playerId, name);
      return cost >= 0 && cost <= this.stash;
    },
    chooseCardDestroy(name: DistrictId) {
      if (!this.canDestroy(name)) return;
      const myTeam = store.getters.getPlayerFromId(store.state.gameState?.self)?.team;
      const theirTeam = store.getters.getPlayerFromId(this.playerId)?.team;
      if (myTeam != null && theirTeam != null && myTeam === theirTeam) {
        this.pendingDestroy = name;
        return;
      }
      this.sendDestroyMove(name);
    },
    cancelDestroy() {
      this.pendingDestroy = null;
    },
    confirmDestroy() {
      if (this.pendingDestroy !== null) {
        this.sendDestroyMove(this.pendingDestroy);
        this.pendingDestroy = null;
      }
    },
    async sendDestroyMove(name: DistrictId) {
      try {
        const move: Move = {
          type: MoveType.WARLORD_DESTROY_DISTRICT,
          data: {
            player: store.getters.getPlayerPosition(this.playerId),
            card: name,
          },
        };
        await store.dispatch('sendMove', move);
      } catch (error) {
        console.log('error when sending move', error);
      }
    },
    async exchangeHand() {
      if (!this.exchangeHandMode) return;

      try {
        const move: Move = {
          type: MoveType.MAGICIAN_EXCHANGE_HAND,
          data: store.getters.getPlayerPosition(this.playerId),
        };
        await store.dispatch('sendMove', move);
      } catch (error) {
        console.log('error when sending move', error);
      }
    },
  },
});
</script>
