// client-react/src/components/game/elements/SeatPanel.tsx
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  DistrictId, Move, MoveType, PlayerBoard,
} from 'citadels-common';
import DistrictCard from './DistrictCard';
import CharacterCard from './CharacterCard';
import Modal from '@/components/common/Modal';
import { cn } from '@/utils/cn';
import {
  useAppStore,
  useGameProgress,
  useCurrentPlayerId,
  selectPlayerFromId,
  selectDistrictDestroyPrice,
  selectPlayerPosition,
} from '@/store';

type BoardWithCrown = PlayerBoard & { crown: boolean };

interface SeatPanelProps {
  playerId: string;
  board: BoardWithCrown;
  pickOrder?: number;
  destroyMode?: boolean;
  exchangeHandMode?: boolean;
  stash?: number;
  relation?: 'self' | 'ally' | 'enemy';
}

// Mirrors Vue elements/SeatPanel.vue. mapGetters → hooks + selectors.
// pendingDestroy data → useState. AppModal → Modal.
export default function SeatPanel({
  playerId,
  board,
  pickOrder = 1,
  destroyMode = false,
  exchangeHandMode = false,
  stash = 0,
  relation = 'enemy',
}: SeatPanelProps) {
  const { t } = useTranslation();
  const gameState = useAppStore((s) => s.gameState);
  const sendMove = useAppStore((s) => s.sendMove);
  const gameProgress = useGameProgress();
  const currentPlayerId = useCurrentPlayerId();
  const [pendingDestroy, setPendingDestroy] = useState<DistrictId | null>(null);

  const getPlayer = selectPlayerFromId(gameState);
  const username = getPlayer(playerId)?.username || playerId;
  const isCurrentPlayer = currentPlayerId === playerId;
  const isActingNow = isCurrentPlayer && gameProgress === 'IN_GAME';

  const roleCard = (() => {
    const chars = (board?.characters || []) as Array<{ id: number; faceDown?: boolean; killed?: boolean; robbed?: boolean }>;
    if (!chars.length) {
      return { show: false, id: 0, faceDown: true, killed: false, robbed: false };
    }
    const revealed = chars.find((c) => c.id > 0 && !c.faceDown);
    if (revealed) {
      return {
        show: true,
        id: revealed.id,
        faceDown: false,
        killed: Boolean(revealed.killed),
        robbed: Boolean(revealed.robbed),
      };
    }
    return { show: true, id: 0, faceDown: true, killed: false, robbed: false };
  })();

  const isAllyTarget = relation === 'ally' || relation === 'self';
  const getDestroyPrice = selectDistrictDestroyPrice(gameState);
  const canDestroy = (name: DistrictId): boolean => {
    if (!destroyMode) return false;
    const cost = getDestroyPrice(playerId, name);
    return cost >= 0 && cost <= stash;
  };

  const getPlayerPos = selectPlayerPosition(gameState);
  const sendDestroyMove = async (name: DistrictId) => {
    try {
      const move: Move = {
        type: MoveType.WARLORD_DESTROY_DISTRICT,
        data: { player: getPlayerPos(playerId), card: name },
      };
      await sendMove(move);
    } catch (error) {
      console.log('error when sending move', error);
    }
  };

  const chooseCardDestroy = (name: DistrictId) => {
    if (!canDestroy(name)) return;
    if (isAllyTarget) {
      setPendingDestroy(name);
      return;
    }
    sendDestroyMove(name);
  };

  const exchangeHand = async () => {
    if (!exchangeHandMode) return;
    try {
      const move: Move = {
        type: MoveType.MAGICIAN_EXCHANGE_HAND,
        data: getPlayerPos(playerId),
      };
      await sendMove(move);
    } catch (error) {
      console.log('error when sending move', error);
    }
  };

  const city = board.city || [];

  return (
    <div className={cn('seat-panel', {
      'seat-panel--ally': relation === 'ally' || relation === 'self',
      'seat-panel--enemy': relation === 'enemy',
      'seat-panel--active': isCurrentPlayer,
      'seat-panel--acting': isActingNow,
    })}>
      <div className="seat-panel__main">
        <div className="seat-panel__banner">
          <span className="seat-panel__pick-no" title={t('ui.game.pick_order_tip')}>{pickOrder}</span>
          <span className="text-truncate flex-fill seat-panel__name">{username}</span>
          {board.crown && <span className="seat-panel__crown" title={t('ui.game.crown_holder')}>👑</span>}
          {relation === 'self' && <span className="seat-panel__tag">{t('ui.lobby.you')}</span>}
          {relation === 'ally' && <span className="seat-panel__tag">{t('ui.team.ally')}</span>}
          {relation === 'enemy' && <span className="seat-panel__tag">{t('ui.team.enemy_short')}</span>}
        </div>

        <div className="seat-panel__stats">
          <div className="seat-panel__stat" title={t('ui.game.stat_gold')}>
            <span className="seat-panel__stat-icon">🪙</span>
            <span className="seat-panel__stat-val">{board.stash ?? 0}</span>
          </div>
          <div
            className={cn('seat-panel__stat', { 'seat-panel__stat--click': exchangeHandMode })}
            title={t('ui.game.stat_hand')}
            onClick={exchangeHand}
          >
            <span className="seat-panel__stat-icon">🃏</span>
            <span className="seat-panel__stat-val">{(board.hand || []).length}</span>
          </div>
          <div className="seat-panel__stat seat-panel__stat--score" title={t('ui.game.stat_score')}>
            <span className="seat-panel__stat-icon">⭐</span>
            <span className="seat-panel__stat-val">{board.score?.total ?? 0}</span>
          </div>
          <div className="seat-panel__stat" title={t('ui.game.stat_city')}>
            <span className="seat-panel__stat-icon">🏛</span>
            <span className="seat-panel__stat-val">{(board.city || []).length}</span>
          </div>
        </div>

        <div className="seat-panel__body">
          <div className="seat-panel__city">
            {city.map((id, i) => id && (
              <DistrictCard
                key={i}
                districtId={id}
                small
                disabled={destroyMode && !canDestroy(id)}
                selectable={canDestroy(id)}
                onSelect={() => chooseCardDestroy(id)}
              />
            ))}
            {!city.length && <div className="seat-panel__city-empty">{t('ui.game.no_buildings')}</div>}
          </div>
          <div className="seat-panel__role">
            {gameProgress === 'IN_GAME' && roleCard.show && (
              <CharacterCard
                characterId={roleCard.id}
                faceDown={roleCard.faceDown}
                killed={roleCard.killed}
                robbed={roleCard.robbed}
                size="medium"
              />
            )}
          </div>
        </div>
      </div>

      <Modal
        show={pendingDestroy !== null}
        title={t('ui.game.destroy_confirm_title')}
        headerClass="bg-warning text-white"
        onClose={() => setPendingDestroy(null)}
        footer={(
          <>
            <button type="button" className="btn btn-secondary" onClick={() => setPendingDestroy(null)}>
              {t('ui.cancel')}
            </button>
            <button
              type="button"
              className="btn btn-danger"
              onClick={() => {
                if (pendingDestroy !== null) {
                  sendDestroyMove(pendingDestroy);
                  setPendingDestroy(null);
                }
              }}
            >
              {t('ui.confirm')}
            </button>
          </>
        )}
      >
        <p>{t('ui.game.warn_destroy_ally', { name: username })}</p>
      </Modal>
    </div>
  );
}

// client/src/components/game/elements/SeatPanel.vue
<template>
  <div
    class="seat-panel"
    :class="{
      'seat-panel--ally':
        relation === 'ally' || relation === 'self',
      'seat-panel--enemy': relation === 'enemy',
      'seat-panel--active': isCurrentPlayer,
      'seat-panel--acting': isActingNow,
    }"
  >
    <div class="seat-panel__main">
      <div class="seat-panel__banner">
        <span
          class="seat-panel__pick-no"
          :title="$t('ui.game.pick_order_tip')"
        >{{ pickOrder }}</span>
        <span class="text-truncate flex-fill seat-panel__name">{{ username }}</span>
        <span
          v-if="board.crown"
          class="seat-panel__crown"
          :title="$t('ui.game.crown_holder')"
        >👑</span>
        <span
          v-if="relation === 'self'"
          class="seat-panel__tag"
        >{{ $t('ui.lobby.you') }}</span>
        <span
          v-else-if="relation === 'ally'"
          class="seat-panel__tag"
        >{{ $t('ui.team.ally') }}</span>
        <span
          v-else-if="relation === 'enemy'"
          class="seat-panel__tag"
        >{{ $t('ui.team.enemy_short') }}</span>
      </div>

      <div class="seat-panel__stats">
        <div class="seat-panel__stat" :title="$t('ui.game.stat_gold')">
          <span class="seat-panel__stat-icon">🪙</span>
          <span class="seat-panel__stat-val">{{ board.stash ?? 0 }}</span>
        </div>
        <div
          class="seat-panel__stat"
          :class="{ 'seat-panel__stat--click': exchangeHandMode }"
          :title="$t('ui.game.stat_hand')"
          @click="exchangeHand"
        >
          <span class="seat-panel__stat-icon">🃏</span>
          <span class="seat-panel__stat-val">{{ (board.hand || []).length }}</span>
        </div>
        <div class="seat-panel__stat seat-panel__stat--score" :title="$t('ui.game.stat_score')">
          <span class="seat-panel__stat-icon">⭐</span>
          <span class="seat-panel__stat-val">{{ board.score?.total ?? 0 }}</span>
        </div>
        <div class="seat-panel__stat" :title="$t('ui.game.stat_city')">
          <span class="seat-panel__stat-icon">🏛</span>
          <span class="seat-panel__stat-val">{{ (board.city || []).length }}</span>
        </div>
      </div>

      <div class="seat-panel__body">
        <div class="seat-panel__city">
          <DistrictCard
            v-for="(id, i) in (board.city || [])"
            :key="i"
            :district-id="id"
            small
            :disabled="destroyMode && !canDestroy(id)"
            :selectable="canDestroy(id)"
            @click="chooseCardDestroy(id)"
          />
          <div v-if="!(board.city || []).length" class="seat-panel__city-empty">
            {{ $t('ui.game.no_buildings') }}
          </div>
        </div>
        <div class="seat-panel__role">
          <CharacterCard
            v-if="gameProgress === 'IN_GAME' && roleCard.show"
            :character-id="roleCard.id"
            :face-down="roleCard.faceDown"
            :killed="roleCard.killed"
            :robbed="roleCard.robbed"
            size="medium"
          />
        </div>
      </div>
    </div>

    <AppModal
      :show="pendingDestroy !== null"
      :title="$t('ui.game.destroy_confirm_title')"
      header-class="bg-warning text-white"
      @close="cancelDestroy"
    >
      <p>{{ $t('ui.game.warn_destroy_ally', { name: username }) }}</p>
      <template #footer>
        <button
          type="button"
          class="btn btn-secondary"
          @click="cancelDestroy"
        >{{ $t('ui.cancel') }}</button>
        <button
          type="button"
          class="btn btn-danger"
          @click="confirmDestroy"
        >{{ $t('ui.confirm') }}</button>
      </template>
    </AppModal>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { mapGetters } from 'vuex';
import {
  DistrictId, Move, MoveType, PlayerBoard,
} from 'citadels-common';
import { store } from '../../../store';
import DistrictCard from './DistrictCard.vue';
import CharacterCard from './CharacterCard.vue';
import AppModal from '../../common/Modal.vue';

type BoardWithCrown = PlayerBoard & { crown: boolean };

export default defineComponent({
  name: 'SeatPanel',
  components: {
    DistrictCard,
    CharacterCard,
    AppModal,
  },
  props: {
    playerId: { type: String, required: true },
    board: { type: Object as () => BoardWithCrown, required: true },
    /** 1-based pick order this round (crown starts at 1) */
    pickOrder: { type: Number, default: 1 },
    destroyMode: { type: Boolean, default: false },
    exchangeHandMode: { type: Boolean, default: false },
    stash: { type: Number, default: 0 },
    relation: { type: String, default: 'enemy' },
  },
  data() {
    return {
      pendingDestroy: null as DistrictId | null,
    };
  },
  computed: {
    ...mapGetters([
      'getPlayerFromId',
      'gameProgress',
      'currentPlayerId',
    ]),
    username() {
      return this.getPlayerFromId(this.playerId)?.username || this.playerId;
    },
    isCurrentPlayer() {
      return this.currentPlayerId === this.playerId;
    },
    /** true when this seat holds the currently called character */
    isActingNow() {
      return this.isCurrentPlayer && this.gameProgress === 'IN_GAME';
    },
    roleCard() {
      const chars = this.board?.characters || [];
      if (!chars.length) {
        return {
          show: false, id: 0, faceDown: true, killed: false, robbed: false,
        };
      }
      const revealed = chars.find((c: any) => c.id > 0 && !c.faceDown);
      if (revealed) {
        return {
          show: true,
          id: revealed.id,
          faceDown: false,
          killed: Boolean(revealed.killed),
          robbed: Boolean(revealed.robbed),
        };
      }
      return {
        show: true,
        id: 0,
        faceDown: true,
        killed: false,
        robbed: false,
      };
    },
  },
  methods: {
    isAllyTarget(): boolean {
      return this.relation === 'ally' || this.relation === 'self';
    },
    canDestroy(name: DistrictId): boolean {
      if (!this.destroyMode) return false;
      const cost = store.getters.getDistrictDestroyPrice(this.playerId, name);
      return cost >= 0 && cost <= this.stash;
    },
    chooseCardDestroy(name: DistrictId) {
      if (!this.canDestroy(name)) return;
      if (this.isAllyTarget()) {
        this.pendingDestroy = name;
        return;
      }
      this.sendDestroyMove(name);
    },
    cancelDestroy() {
      this.pendingDestroy = null;
    },
    confirmDestroy() {
      if (this.pendingDestroy !== null) {
        this.sendDestroyMove(this.pendingDestroy);
        this.pendingDestroy = null;
      }
    },
    async sendDestroyMove(name: DistrictId) {
      try {
        const move: Move = {
          type: MoveType.WARLORD_DESTROY_DISTRICT,
          data: {
            player: store.getters.getPlayerPosition(this.playerId),
            card: name,
          },
        };
        await store.dispatch('sendMove', move);
      } catch (error) {
        console.log('error when sending move', error);
      }
    },
    async exchangeHand() {
      if (!this.exchangeHandMode) return;
      try {
        const move: Move = {
          type: MoveType.MAGICIAN_EXCHANGE_HAND,
          data: store.getters.getPlayerPosition(this.playerId),
        };
        await store.dispatch('sendMove', move);
      } catch (error) {
        console.log('error when sending move', error);
      }
    },
  },
});
</script>
