// client-react/src/components/AuthPanel.tsx
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { createPortal } from 'react-dom';
import { useAppStore } from '@/store';

// Mirrors Vue AuthPanel.vue. The two modals (auth + profile) use createPortal.
// The Vue `mounted` window 'open-auth' listener becomes useEffect. Vue data()
// fields → useState. mapGetters (isLoggedIn/authUser/authReady) → store hooks.
export default function AuthPanel() {
  const { t } = useTranslation();
  const authUser = useAppStore((s) => s.authUser);
  const authReady = useAppStore((s) => s.authReady);
  const authToken = useAppStore((s) => s.authToken);
  const login = useAppStore((s) => s.login);
  const register = useAppStore((s) => s.register);
  const logout = useAppStore((s) => s.logout);
  const updateDisplayName = useAppStore((s) => s.updateDisplayName);

  const isLoggedIn = Boolean(authToken && authUser);

  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [profileDisplayName, setProfileDisplayName] = useState('');
  const [error, setError] = useState('');
  const [profileError, setProfileError] = useState('');
  const [profileOk, setProfileOk] = useState(false);
  const [busy, setBusy] = useState(false);
  const [showAuthModal, setShowAuthModal] = useState(false);
  const [showProfileModal, setShowProfileModal] = useState(false);

  // Vue watch showProfileModal → reset profile fields. Mirror via effect.
  useEffect(() => {
    if (showProfileModal) {
      setProfileDisplayName(authUser?.displayName || '');
      setProfileError('');
      setProfileOk(false);
    }
  }, [showProfileModal, authUser]);

  // Vue mounted: window 'open-auth' listener. Mirror via effect.
  useEffect(() => {
    const onOpenAuth = () => setShowAuthModal(true);
    window.addEventListener('open-auth', onOpenAuth);
    return () => window.removeEventListener('open-auth', onOpenAuth);
  }, []);

  const openAuth = (m: 'login' | 'register') => {
    setMode(m);
    setError('');
    setPassword('');
    setShowAuthModal(true);
  };

  const submitAuth = async () => {
    setBusy(true);
    setError('');
    try {
      if (mode === 'login') {
        await login(username.trim(), password);
      } else {
        await register({
          username: username.trim(),
          password,
          displayName: displayName.trim() || undefined,
        });
      }
      setShowAuthModal(false);
      setPassword('');
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  const saveProfile = async () => {
    setBusy(true);
    setProfileError('');
    setProfileOk(false);
    try {
      await updateDisplayName(profileDisplayName.trim());
      setProfileOk(true);
    } catch (e) {
      setProfileError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  if (!authReady) {
    return (
      <div className="auth-panel text-right">
        <small className="text-muted">...</small>
      </div>
    );
  }

  if (isLoggedIn && authUser) {
    return (
      <div className="auth-panel text-right">
        <div className="d-flex flex-column align-items-end">
          <span className="small">
            {authUser.displayName}
            <span className="badge badge-success">{t('ui.auth.logged_in')}</span>
          </span>
          <div className="btn-group btn-group-sm mt-1">
            <button type="button" className="btn btn-outline-light btn-sm" onClick={() => setShowProfileModal(true)}>
              {t('ui.auth.profile')}
            </button>
            <button type="button" className="btn btn-outline-light btn-sm" onClick={logout}>
              {t('ui.auth.logout')}
            </button>
          </div>
        </div>

        {showAuthModal && createPortal(
          <div className="modal fade show d-block" style={{ background: 'rgba(0,0,0,0.65)', zIndex: 1050 }}>
            <div className="modal-dialog modal-dialog-centered">
              <div className="modal-content text-dark text-left">
                <div className="modal-header">
                  <h5 className="modal-title">
                    {mode === 'login' ? t('ui.auth.login') : t('ui.auth.register')}
                  </h5>
                  <button type="button" className="close" aria-label={t('ui.close') as string} onClick={() => setShowAuthModal(false)}>
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div className="modal-body">
                  {error && <div className="alert alert-danger py-2">{error}</div>}
                  <div className="form-group">
                    <label>{t('ui.auth.username')}</label>
                    <input className="form-control" value={username} autoComplete="username" onChange={(e) => setUsername(e.target.value)} />
                  </div>
                  <div className="form-group">
                    <label>{t('ui.auth.password')}</label>
                    <input
                      className="form-control"
                      type="password"
                      value={password}
                      autoComplete="current-password"
                      onChange={(e) => setPassword(e.target.value)}
                    />
                  </div>
                  {mode === 'register' && (
                    <div className="form-group">
                      <label>{t('ui.auth.display_name')}</label>
                      <input
                        className="form-control"
                        value={displayName}
                        placeholder={t('ui.auth.display_name_hint') as string}
                        onChange={(e) => setDisplayName(e.target.value)}
                      />
                    </div>
                  )}
                </div>
                <div className="modal-footer">
                  <button
                    type="button"
                    className="btn btn-link"
                    onClick={() => setMode(mode === 'login' ? 'register' : 'login')}
                  >
                    {mode === 'login' ? t('ui.auth.switch_to_register') : t('ui.auth.switch_to_login')}
                  </button>
                  <button type="button" className="btn btn-primary" disabled={busy} onClick={submitAuth}>
                    {mode === 'login' ? t('ui.auth.login') : t('ui.auth.register')}
                  </button>
                </div>
              </div>
            </div>
          </div>,
          document.body,
        )}

        {showProfileModal && createPortal(
          <div className="modal fade show d-block" style={{ background: 'rgba(0,0,0,0.65)', zIndex: 1050 }}>
            <div className="modal-dialog modal-dialog-centered">
              <div className="modal-content text-dark text-left">
                <div className="modal-header">
                  <h5 className="modal-title">{t('ui.auth.profile')}</h5>
                  <button type="button" className="close" aria-label={t('ui.close') as string} onClick={() => setShowProfileModal(false)}>
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div className="modal-body">
                  {profileError && <div className="alert alert-danger py-2">{profileError}</div>}
                  {profileOk && <div className="alert alert-success py-2">{t('ui.auth.saved')}</div>}
                  <p className="mb-2">
                    <strong>{t('ui.auth.username')}:</strong>
                    {authUser?.username}
                  </p>
                  <div className="form-group mb-0">
                    <label>{t('ui.auth.display_name')}</label>
                    <input className="form-control" value={profileDisplayName} onChange={(e) => setProfileDisplayName(e.target.value)} />
                  </div>
                </div>
                <div className="modal-footer">
                  <button type="button" className="btn btn-secondary" onClick={() => setShowProfileModal(false)}>
                    {t('ui.close')}
                  </button>
                  <button type="button" className="btn btn-primary" disabled={busy} onClick={saveProfile}>
                    {t('ui.confirm')}
                  </button>
                </div>
              </div>
            </div>
          </div>,
          document.body,
        )}
      </div>
    );
  }

  return (
    <div className="auth-panel text-right">
      <span className="badge badge-secondary mr-1">{t('ui.auth.guest')}</span>
      <button type="button" className="btn btn-sm btn-light" onClick={() => openAuth('login')}>
        {t('ui.auth.login')}
      </button>
      <button type="button" className="btn btn-sm btn-outline-light ml-1" onClick={() => openAuth('register')}>
        {t('ui.auth.register')}
      </button>
    </div>
  );
}

// client/src/components/AuthPanel.vue
<template>
<div class="auth-panel text-right">
  <template v-if="!authReady">
    <small class="text-muted">...</small>
  </template>
  <template v-else-if="isLoggedIn && authUser">
    <div class="d-flex flex-column align-items-end">
      <span class="small">
        {{ authUser.displayName }}
        <span class="badge badge-success">{{ $t('ui.auth.logged_in') }}</span>
      </span>
      <div class="btn-group btn-group-sm mt-1">
        <button type="button" class="btn btn-outline-light btn-sm" @click="showProfileModal = true">
          {{ $t('ui.auth.profile') }}
        </button>
        <button type="button" class="btn btn-outline-light btn-sm" @click="logout">
          {{ $t('ui.auth.logout') }}
        </button>
      </div>
    </div>
  </template>
  <template v-else>
    <span class="badge badge-secondary mr-1">{{ $t('ui.auth.guest') }}</span>
    <button type="button" class="btn btn-sm btn-light" @click="openAuth('login')">
      {{ $t('ui.auth.login') }}
    </button>
    <button type="button" class="btn btn-sm btn-outline-light ml-1" @click="openAuth('register')">
      {{ $t('ui.auth.register') }}
    </button>
  </template>

  <div
    v-if="showAuthModal"
    class="modal fade show d-block"
    style="background:rgba(0,0,0,0.65); z-index: 1050;"
  >
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content text-dark text-left">
        <div class="modal-header">
          <h5 class="modal-title">
            {{ mode === 'login' ? $t('ui.auth.login') : $t('ui.auth.register') }}
          </h5>
          <button type="button" class="close" :aria-label="$t('ui.close')" @click="showAuthModal = false">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div v-if="error" class="alert alert-danger py-2">{{ error }}</div>
          <div class="form-group">
            <label>{{ $t('ui.auth.username') }}</label>
            <input class="form-control" v-model="username" autocomplete="username" />
          </div>
          <div class="form-group">
            <label>{{ $t('ui.auth.password') }}</label>
            <input
              class="form-control"
              type="password"
              v-model="password"
              autocomplete="current-password"
            />
          </div>
          <div class="form-group" v-if="mode === 'register'">
            <label>{{ $t('ui.auth.display_name') }}</label>
            <input
              class="form-control"
              v-model="displayName"
              :placeholder="$t('ui.auth.display_name_hint')"
            />
          </div>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-link"
            @click="mode = mode === 'login' ? 'register' : 'login'"
          >
            {{ mode === 'login'
              ? $t('ui.auth.switch_to_register')
              : $t('ui.auth.switch_to_login') }}
          </button>
          <button type="button" class="btn btn-primary" :disabled="busy" @click="submitAuth">
            {{ mode === 'login' ? $t('ui.auth.login') : $t('ui.auth.register') }}
          </button>
        </div>
      </div>
    </div>
  </div>

  <div
    v-if="showProfileModal"
    class="modal fade show d-block"
    style="background:rgba(0,0,0,0.65); z-index: 1050;"
  >
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content text-dark text-left">
        <div class="modal-header">
          <h5 class="modal-title">{{ $t('ui.auth.profile') }}</h5>
          <button type="button" class="close" :aria-label="$t('ui.close')" @click="showProfileModal = false">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div v-if="profileError" class="alert alert-danger py-2">{{ profileError }}</div>
          <div v-if="profileOk" class="alert alert-success py-2">{{ $t('ui.auth.saved') }}</div>
          <p class="mb-2">
            <strong>{{ $t('ui.auth.username') }}:</strong>
            {{ authUser?.username }}
          </p>
          <div class="form-group mb-0">
            <label>{{ $t('ui.auth.display_name') }}</label>
            <input class="form-control" v-model="profileDisplayName" />
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" @click="showProfileModal = false">
            {{ $t('ui.close') }}
          </button>
          <button type="button" class="btn btn-primary" :disabled="busy" @click="saveProfile">
            {{ $t('ui.confirm') }}
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { mapGetters } from 'vuex';
import { store } from '../store';

export default defineComponent({
  name: 'AuthPanel',
  data() {
    return {
      mode: 'login' as 'login' | 'register',
      username: '',
      password: '',
      displayName: '',
      profileDisplayName: '',
      error: '',
      profileError: '',
      profileOk: false,
      busy: false,
      showAuthModal: false,
      showProfileModal: false,
    };
  },
  computed: {
    ...mapGetters(['isLoggedIn', 'authUser', 'authReady']),
  },
  watch: {
    showProfileModal(val) {
      if (val) {
        this.profileDisplayName = this.authUser?.displayName || '';
        this.profileError = '';
        this.profileOk = false;
      }
    },
  },
  mounted() {
    window.addEventListener('open-auth', this.onOpenAuth);
  },
  unmounted() {
    window.removeEventListener('open-auth', this.onOpenAuth);
  },
  methods: {
    onOpenAuth() {
      this.showAuthModal = true;
    },
    openAuth(mode: 'login' | 'register') {
      this.mode = mode;
      this.error = '';
      this.password = '';
      this.showAuthModal = true;
    },
    async submitAuth() {
      this.busy = true;
      this.error = '';
      try {
        if (this.mode === 'login') {
          await store.dispatch('login', {
            username: this.username.trim(),
            password: this.password,
          });
        } else {
          await store.dispatch('register', {
            username: this.username.trim(),
            password: this.password,
            displayName: this.displayName.trim() || undefined,
          });
        }
        this.showAuthModal = false;
        this.password = '';
      } catch (e: any) {
        this.error = e?.message || String(e);
      } finally {
        this.busy = false;
      }
    },
    async logout() {
      await store.dispatch('logout');
    },
    async saveProfile() {
      this.busy = true;
      this.profileError = '';
      this.profileOk = false;
      try {
        await store.dispatch('updateDisplayName', this.profileDisplayName.trim());
        this.profileOk = true;
      } catch (e: any) {
        this.profileError = e?.message || String(e);
      } finally {
        this.busy = false;
      }
    },
  },
});
</script>
