// client-react/src/components/CardsPreview.tsx
import { useMemo } from 'react';
import { districts, type DistrictId } from 'citadels-common';
import DistrictCard from '@/components/game/elements/DistrictCard';

// Mirrors Vue CardsPreview.vue — shows every district card in both sizes.
export default function CardsPreview() {
  const cards = useMemo(() => Object.keys(districts) as DistrictId[], []);

  return (
    <div className="container-lg d-flex justify-content-center flex-wrap">
      {cards.map((card) => (
        <DistrictCard key={card} districtId={card} className="m-1" />
      ))}
      <div className="w-100" />
      {cards.map((card) => (
        <DistrictCard key={card} districtId={card} className="m-1" small />
      ))}
    </div>
  );
}

// client/src/components/CardsPreview.vue
<template>
<div class="container-lg d-flex justify-content-center flex-wrap">
  <DistrictCard
    v-for="card in cards"
    :key="card"
    :district-id="card"
    class="m-1"
  />
  <div class="w-100"></div>
  <DistrictCard
    v-for="card in cards"
    :key="card"
    :district-id="card"
    class="m-1"
    small
  />
</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { districts, DistrictId } from 'citadels-common';
import DistrictCard from './game/elements/DistrictCard.vue';

export default defineComponent({
  name: 'CardsPreview',
  components: {
    DistrictCard,
  },
  computed: {
    cards(): DistrictId[] {
      return Object.keys(districts) as DistrictId[];
    },
  },
});
</script>
